import type { BreakpointClass } from '@/consts/layout';
import type { NodesConnection } from '@/utils/connection';

export type SettingsState = {
  appConnection: NodesConnection;
  userDisclaimerApprove: boolean;
  language: string;
  displayRegions: Nullable<Intl.DisplayNames>;
  percentFormat: Nullable<Intl.NumberFormat>;
  menuCollapsed: boolean;
  selectNodeDialogVisibility: boolean;
  selectIndexerDialogVisibility: boolean;
  selectLanguageDialogVisibility: boolean;
  selectCurrencyDialogVisibility: boolean;
  rotatePhoneDialogVisibility: boolean;
  disclaimerVisibility: boolean;
  alertSettingsVisibility: boolean;
  browserNotifPopupVisibility: boolean;
  browserNotifPopupBlockedVisibility: boolean;
  isBrowserNotificationApiAvailable: boolean;
  browserNotifsPermission: NotificationPermission;
  internetConnection: Nullable<boolean>;
  internetConnectionSpeed: Nullable<number>;
  screenBreakpointClass: BreakpointClass;
  windowWidth: number;
  isTMA: boolean;
  telegramBotUrl: Nullable<string>;
  isRotatePhoneHideBalanceFeatureEnabled: boolean;
  isOrientationWarningVisible: boolean;
  isAccessAccelerometrEventDeclined: boolean;
  isAccessRotationListener: boolean;
  isThemePreference: boolean;
};
