export enum Currency {
  DAI = 'dai',
  USD = 'usd',
  XOR = 'xor',
  AED = 'aed',
  ARS = 'ars',
  AUD = 'aud',
  BDT = 'bdt',
  BHD = 'bhd',
  BMD = 'bmd',
  GBP = 'gbp',
  BRL = 'brl',
  CAD = 'cad',
  CHF = 'chf',
  CLP = 'clp',
  CNY = 'cny',
  CZK = 'czk',
  DKK = 'dkk',
  EUR = 'eur',
  GEL = 'gel',
  HKD = 'hkd',
  HUF = 'huf',
  IDR = 'idr',
  ILS = 'ils',
  INR = 'inr',
  JPY = 'jpy',
  KRW = 'krw',
  KWD = 'kwd',
  LKR = 'lkr',
  MMK = 'mmk',
  MXN = 'mxn',
  MYR = 'myr',
  NGN = 'ngn',
  NOK = 'nok',
  NZD = 'nzd',
  PHP = 'php',
  PKR = 'pkr',
  PLN = 'pln',
  RUB = 'rub',
  SAR = 'sar',
  SEK = 'sek',
  SGD = 'sgd',
  TRY = 'try',
  THB = 'thb',
  TWD = 'twd',
  UAH = 'uah',
  VEF = 'vef',
  VND = 'vnd',
  XAG = 'xag',
  XAU = 'xau',
  SDR = 'sdr',
  ZAR = 'zar',
}

export type FiatExchangeRateObject = Record<string, number>;

export interface CurrencyFields {
  key: Currency;
  name: string;
  symbol: string;
  disabled?: boolean;
}
