import {
  addGDriveWalletLocally,
  addSoraWalletLocally,
  addWcSubWalletLocally,
  beforeTransactionSign,
  checkCameraPermission,
  checkDevicesAvailability,
  delay,
  formatAccountAddress,
  getAccountIdentity,
  getCssVariableValue,
  getExplorerLinks,
  getScrollbarWidth,
  groupRewardsByAssetsList,
  translationUtils,
} from '../../index';

export {
  addGDriveWalletLocally,
  addSoraWalletLocally,
  addWcSubWalletLocally,
  beforeTransactionSign,
  checkCameraPermission,
  checkDevicesAvailability,
  delay,
  formatAccountAddress,
  getAccountIdentity,
  getCssVariableValue,
  getExplorerLinks,
  getScrollbarWidth,
  groupRewardsByAssetsList,
  translationUtils,
};

export default {
  addGDriveWalletLocally,
  addSoraWalletLocally,
  addWcSubWalletLocally,
  beforeTransactionSign,
  checkCameraPermission,
  checkDevicesAvailability,
  delay,
  formatAccountAddress,
  getAccountIdentity,
  getCssVariableValue,
  getExplorerLinks,
  getScrollbarWidth,
  groupRewardsByAssetsList,
  translationUtils,
};
