/** Write-once engineering report. All observations are generated by the fixed synthetic harness. */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { runGoalSyntheticReachability } from './goal-synthetic-reachability';

/** Validate the single output argument before running the fixed local-only scenarios. */
async function main() {
  if (process.argv.length !== 3)
    throw Error('Usage: tsx scripts/bots/run-goal-synthetic-reachability.ts OUTPUT_DIRECTORY');
  const output = resolve(process.argv[2]);
  await mkdir(output, { recursive: true });
  const report = runGoalSyntheticReachability();
  await writeFile(join(output, 'report.json'), JSON.stringify(report, null, 2) + '\n', { flag: 'wx' });
  process.stdout.write(
    JSON.stringify({
      kind: report.kind,
      cases: report.cases.length,
      output: join(output, 'report.json'),
      qualificationEligible: false,
      networkAttempts: 0,
    }) + '\n'
  );
}
main().catch((error: unknown) => {
  process.stderr.write(String(error) + '\n');
  process.exitCode = 1;
});
