import type { WalletGettersDecorators } from './types';
import type { VueDecorator } from 'vue-class-component';
declare const walletGetter: WalletGettersDecorators;
declare const state: {
  account: {
    address: VueDecorator;
    name: VueDecorator;
    source: VueDecorator;
    isExternal: VueDecorator;
    book: VueDecorator;
    accountPasswordTimeout: VueDecorator;
    pinnedAssets: VueDecorator;
    assets: VueDecorator;
    assetsSubscription: VueDecorator;
    accountAssets: VueDecorator;
    alertSubject: VueDecorator;
    accountAssetsSubscription: VueDecorator;
    whitelistArray: VueDecorator;
    blacklistArray: VueDecorator;
    fiatPriceObject: VueDecorator;
    fiatPriceSubscription: VueDecorator;
    ceresFiatValuesUsage: VueDecorator;
    availableWallets: VueDecorator;
    addressKeyMapping: VueDecorator;
    addressPassphraseMapping: VueDecorator;
    assetsToNotifyQueue: VueDecorator;
    isDesktop: VueDecorator;
    accountPasswordTimer: VueDecorator;
    accountPasswordTimestamp: VueDecorator;
    isMstAddressExist: VueDecorator;
    isMST: VueDecorator;
  };
  router: {
    currentRoute: VueDecorator;
    currentRouteParams: VueDecorator;
    previousRoute: VueDecorator;
    previousRouteParams: VueDecorator;
  };
  settings: {
    filters: VueDecorator;
    shouldBalanceBeHidden: VueDecorator;
    networkFees: VueDecorator;
    feeMultiplier: VueDecorator;
    alerts: VueDecorator;
    allowFeePopup: VueDecorator;
    indexerType: VueDecorator;
    currency: VueDecorator;
    theme: VueDecorator;
    soraNetwork: VueDecorator;
    apiKeys: VueDecorator;
    allowTopUpAlert: VueDecorator;
    isWalletLoaded: VueDecorator;
    indexers: VueDecorator;
    permissions: VueDecorator;
    runtimeVersion: VueDecorator;
    blockNumber: VueDecorator;
    blockNumberSubscription: VueDecorator;
    feeMultiplierAndRuntimeSubscriptions: VueDecorator;
    nftStorage: VueDecorator;
    currencies: VueDecorator;
    fiatExchangeRateObject: VueDecorator;
    exchangeRateUnsubFn: VueDecorator;
    assetsFilter: VueDecorator;
    isMSTAvailable: VueDecorator;
  };
  subscriptions: {
    storageUpdatesSubscription: VueDecorator;
  };
  transactions: {
    history: VueDecorator;
    saveExternalHistoryUpdates: VueDecorator;
    externalHistory: VueDecorator;
    externalHistoryUpdates: VueDecorator;
    externalHistoryTotal: VueDecorator;
    externalHistorySubscription: VueDecorator;
    activeTxsIds: VueDecorator;
    updateActiveTxsId: VueDecorator;
    selectedTxId: VueDecorator;
    isConfirmTxDialogDisabled: VueDecorator;
    isSignTxDialogDisabled: VueDecorator;
    isSignTxDialogVisible: VueDecorator;
    pendingMstTxsSubscription: VueDecorator;
    pendingMstTransactions: VueDecorator;
  };
};
declare const getter: typeof walletGetter.wallet & {
  libraryDesignSystem: VueDecorator;
  libraryTheme: VueDecorator;
};
declare const mutation: {
  account: {
    setFiatPriceObject: VueDecorator;
    updateFiatPriceObject: VueDecorator;
    clearFiatPriceObject: VueDecorator;
    setAlertSubject: VueDecorator;
    resetAlertSubscription: VueDecorator;
    setFiatPriceSubscription: VueDecorator;
    resetFiatPriceSubscription: VueDecorator;
    setCeresFiatValuesUsage: VueDecorator;
    resetAccount: VueDecorator;
    setAssetsSubscription: VueDecorator;
    resetAssetsSubscription: VueDecorator;
    setAccountAssetsSubscription: VueDecorator;
    resetAccountAssetsSubscription: VueDecorator;
    syncWithStorage: VueDecorator;
    setAssets: VueDecorator;
    setAccountAssets: VueDecorator;
    setPinnedAsset: VueDecorator;
    setMultiplePinnedAssets: VueDecorator;
    removePinnedAsset: VueDecorator;
    setAssetToNotify: VueDecorator;
    popAssetFromNotificationQueue: VueDecorator;
    setWhitelist: VueDecorator;
    setNftBlacklist: VueDecorator;
    clearWhitelist: VueDecorator;
    clearBlacklist: VueDecorator;
    setAvailableWallets: VueDecorator;
    setAccountPassphrase: VueDecorator;
    resetAccountPassphrase: VueDecorator;
    setPasswordTimeout: VueDecorator;
    setAccountPassphraseTimer: VueDecorator;
    resetAccountPassphraseTimer: VueDecorator;
    setIsDesktop: VueDecorator;
    setAddressToBook: VueDecorator;
    removeAddressFromBook: VueDecorator;
    setIsMstAddressExist: VueDecorator;
    setIsMST: VueDecorator;
  };
  router: {
    navigate: VueDecorator;
  };
  settings: {
    setIndexerType: VueDecorator;
    setIndexerStatus: VueDecorator;
    setIndexerEndpoint: VueDecorator;
    setWalletLoaded: VueDecorator;
    setPermissions: VueDecorator;
    setSoraNetwork: VueDecorator;
    setNetworkFees: VueDecorator;
    updateNetworkFees: VueDecorator;
    toggleHideBalance: VueDecorator;
    setFilterOptions: VueDecorator;
    setAllowFeePopup: VueDecorator;
    setFeeMultiplier: VueDecorator;
    setRuntimeVersion: VueDecorator;
    setBlockNumber: VueDecorator;
    setBlockNumberSubscription: VueDecorator;
    resetBlockNumberSubscription: VueDecorator;
    setFeeMultiplierAndRuntimeSubscriptions: VueDecorator;
    resetFeeMultiplierAndRuntimeSubscriptions: VueDecorator;
    setApiKeys: VueDecorator;
    setNftStorage: VueDecorator;
    setDepositNotifications: VueDecorator;
    addPriceAlert: VueDecorator;
    removePriceAlert: VueDecorator;
    editPriceAlert: VueDecorator;
    setPriceAlertAsNotified: VueDecorator;
    setFiatCurrency: VueDecorator;
    setCurrencies: VueDecorator;
    updateFiatExchangeRates: VueDecorator;
    setExchangeRateUnsubFn: VueDecorator;
    resetExchangeRateSubscription: VueDecorator;
    setAssetsFilter: VueDecorator;
    setIsMstAvailable: VueDecorator;
    setTheme: VueDecorator;
  };
  subscriptions: {
    setSubscription: VueDecorator;
  };
  transactions: {
    setActiveTxsSubscription: VueDecorator;
    resetActiveTxs: VueDecorator;
    addActiveTx: VueDecorator;
    removeActiveTxs: VueDecorator;
    removeHistoryByIds: VueDecorator;
    setTxDetailsId: VueDecorator;
    resetTxDetailsId: VueDecorator;
    getHistory: VueDecorator;
    setExternalHistory: VueDecorator;
    setExternalHistoryUpdates: VueDecorator;
    saveExternalHistoryUpdates: VueDecorator;
    setExternalHistoryTotal: VueDecorator;
    resetExternalHistory: VueDecorator;
    setExternalHistorySubscription: VueDecorator;
    resetExternalHistorySubscription: VueDecorator;
    setConfirmTxDialogDisabled: VueDecorator;
    setSignTxDialogDisabled: VueDecorator;
    setSignTxDialogVisibility: VueDecorator;
    setPendingMstTxsSubscription: VueDecorator;
    resetPendingMstTxsSubscription: VueDecorator;
    setPendingMstTransactions: VueDecorator;
  };
};
declare const action: {
  account: {
    logout: VueDecorator;
    addAsset: VueDecorator;
    transfer: VueDecorator;
    vestedTransfer: VueDecorator;
    resetFiatPriceSubscription: VueDecorator;
    resetAssetsSubscription: VueDecorator;
    resetAccountAssetsSubscription: VueDecorator;
    syncWithStorage: VueDecorator;
    setAccountPassphrase: VueDecorator;
    resetAccountPassphrase: VueDecorator;
    afterLogin: VueDecorator;
    checkWalletAvailability: VueDecorator;
    checkConnectedAccountSource: VueDecorator;
    updateAvailableWallets: VueDecorator;
    loginAccount: VueDecorator;
    renameAccount: VueDecorator;
    getAssets: VueDecorator;
    subscribeOnAssets: VueDecorator;
    subscribeOnAccountAssets: VueDecorator;
    getWhitelist: VueDecorator;
    getNftBlacklist: VueDecorator;
    subscribeOnAlerts: VueDecorator;
    subscribeOnFiatPrice: VueDecorator;
    useCeresApiForFiatValues: VueDecorator;
    notifyOnDeposit: VueDecorator;
    getVestedTransferFee: VueDecorator;
    resetAlertsSubscription: VueDecorator;
    initMultisigAddress: VueDecorator;
  };
  router: {
    back: VueDecorator;
    checkCurrentRoute: VueDecorator;
  };
  settings: {
    setIndexerStatus: VueDecorator;
    resetBlockNumberSubscription: VueDecorator;
    resetFeeMultiplierAndRuntimeSubscriptions: VueDecorator;
    setApiKeys: VueDecorator;
    setTheme: VueDecorator;
    createNftStorageInstance: VueDecorator;
    subscribeOnFeeMultiplierAndRuntime: VueDecorator;
    subscribeOnBlockNumber: VueDecorator;
    selectIndexer: VueDecorator;
    subscribeOnExchangeRatesApi: VueDecorator;
    toggleTheme: VueDecorator;
  };
  subscriptions: {
    resetStorageUpdatesSubscription: VueDecorator;
    subscribeToStorageUpdates: VueDecorator;
    activateNetwokSubscriptions: VueDecorator;
    resetNetworkSubscriptions: VueDecorator;
    activateIndexerSubscriptions: VueDecorator;
    resetIndexerSubscriptions: VueDecorator;
    activateInternalSubscriptions: VueDecorator;
    resetInternalSubscriptions: VueDecorator;
  };
  transactions: {
    resetActiveTxs: VueDecorator;
    resetExternalHistorySubscription: VueDecorator;
    resetPendingMstTxsSubscription: VueDecorator;
    subscribeOnExternalHistory: VueDecorator;
    getExternalHistory: VueDecorator;
    trackActiveTxs: VueDecorator;
    trackPendingMstTxs: VueDecorator;
    getAccountHistory: VueDecorator;
  };
};
export { state, getter, mutation, action };
