compressionLevel: 0

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  '@reown/appkit@*':
    dependencies:
      '@types/react': 'npm:19.2.2'
  '@typescript-eslint/utils@*':
    dependencies:
      'typescript': 'npm:~5.9.3'
  'cssstyle@*':
    dependencies:
      'postcss': 'npm:^8.5.6'
  '@open-web3/api-mobx@*':
    peerDependencies:
      '@polkadot/api': '>=5.0.0'
    peerDependenciesMeta:
      '@polkadot/api':
        optional: true
  '@open-web3/orml-api-derive@*':
    peerDependencies:
      '@polkadot/api': '>=6.3.1'
  '@open-web3/orml-types@*':
    peerDependencies:
      '@polkadot/api': '>=6.3.1'
