import { History } from '@sora-substrate/sdk';
import { KnownSymbols } from '@sora-substrate/sdk/build/assets/consts';
import { SoraNetwork, WalletPermissions } from '@/consts';
import type { PolkadotJsAccount, WhitelistIdsBySymbol } from '../../src/types/common';
import type { AccountAsset, Asset, Whitelist } from '@sora-substrate/sdk/build/assets/types';
export declare const MOCK_NETWORK_FEE: import('@sora-substrate/sdk').NetworkFeesObject;
export declare const MOCK_ACCOUNT_ASSETS: Array<AccountAsset>;
export declare const MOCK_ACCOUNT_ASSETS_NFT: {
  address: string;
  balance: {
    transferable: string;
    total: string;
    free: string;
    reserved: string;
    frozen: string;
    locked: string;
    bonded: string;
  };
  content: string;
  decimals: number;
  name: string;
  symbol: string;
  description: string;
}[];
export declare const MOCK_ASSETS: Array<Asset>;
export declare const MOCK_ASSETS_TABLE: {
  '0x0200000000000000000000000000000000000000000000000000000000000000': {
    address: string;
    symbol: KnownSymbols;
    name: string;
    decimals: number;
    isMintable: boolean;
  };
};
export declare const MOCK_HISTORY: Array<History>;
export declare const MOCK_ACCOUNT_HISTORY: {};
export declare const MOCK_EXTERNAL_HISTORY: {
  '0x19cd61b49e9b3549a2718e1edae8828c7915a186b065044145a5e2e67d736069': {
    id: string;
    type: string;
    txId: string;
    blockId: string;
    blockHeight: string;
    endTime: number;
    startTime: number;
    from: string;
    soraNetworkFee: string;
    status: string;
    assetAddress: string;
    symbol: string;
    to: string;
    amount: string;
  };
  '0xc991cf9f6eb03b019f0f87ea59a9bc4c0d325ee53f63d86121eedebf09d2dcfc': {
    id: string;
    type: string;
    txId: string;
    blockId: string;
    blockHeight: string;
    endTime: number;
    startTime: number;
    from: string;
    soraNetworkFee: string;
    status: string;
    assetAddress: string;
    symbol: string;
    to: string;
    amount: string;
  };
  '0x39d9cd49d00fb4267e03c8c0355e4758546b0637845a05fac2ccce09eadfcda1': {
    id: string;
    type: string;
    txId: string;
    blockId: string;
    blockHeight: string;
    endTime: number;
    startTime: number;
    from: string;
    soraNetworkFee: string;
    status: string;
    assetAddress: string;
    symbol: string;
    to: string;
    amount: string;
  };
  '0x4e3de4b012fe63e2fd8ec2ef096bf2def66d05cd0a81dbcb37a65d110e937ec3': {
    id: string;
    type: string;
    txId: string;
    blockId: string;
    blockHeight: string;
    endTime: number;
    startTime: number;
    from: string;
    soraNetworkFee: string;
    status: string;
    assetAddress: string;
    symbol: string;
    to: string;
    amount: string;
  };
};
export declare const MOCK_ACCOUNTS: any;
export declare const MOCK_WHITE_LIST: Whitelist;
export declare const MOCK_WHITELIST_IDS_BY_SYMBOL: WhitelistIdsBySymbol;
export declare const MOCK_FIAT_PRICE_OBJECT: any;
export declare const MOCK_SORA_NETWORK = SoraNetwork.Dev;
export declare const MOCK_ACCOUNT: PolkadotJsAccount;
export declare const MOCK_POLKADOTJS_ACCOUNTS: Array<PolkadotJsAccount>;
export declare const MOCK_WALLET_PERMISSIONS: WalletPermissions;
