"""Save the researched Gulf and Middle East personal postal tea findings."""
import json
from pathlib import Path
p=Path(__file__).parent
M='https://www.maff.go.jp/pps/j/search/e_hayami_yubin.pdf?d=1702'
rows=[]
def add(code,status,rule,mail,urls,question,attempts,quantity=None):
 rows.append(dict(code=code,status=status,rule=rule,personalMailApplicability=mail,quantityLimit=quantity,authority='Destination agricultural/food authority; Japan MAFF Plant Protection Station where cited',evidenceUrls=urls,remainingQuestion=question,researchAttempts=attempts,reviewedAt='2026-09-29'))
add('AE','permit_required',
 'Certificate route unless a processing exemption is confirmed: MAFF postal matrix AE=Q*11. UAE agricultural-quarantine law Articles 1 and 3 covers regulated plant products, including manufactured products presenting pest risk. The personal-food pathway under Resolution 14/2016 also requires recipient-labelled packages and shipment documents identifying food, quantity, expiry and recipient. The published food-category list does not identify dry tea clearly enough to assign it a numeric allowance.',
 'MAFF evidence specifically concerns manufactured green tea sent from Japan by post. UAE personal-food guidance explicitly includes unaccompanied shipments; baggage is excepted only from some labelling/document requirements.',
 [M,'https://uaelegislation.gov.ae/en/legislations/3995','https://uaecabinet.ae/ar/news/minister-of-environment-issues-ministerial-resolution-on-control-of-imported-food-for-non-commercial-purposes','https://www.moccae.gov.ae/ar/services/release-of-agricultural-products-consignment'],
 'MOCCAE must determine whether this steamed/dried sealed sencha qualifies for the processing waiver; otherwise arrange Japanese phytosanitary certification. Also establish the personal-food quantity category with the receiving emirate. No blanket clearance for 24.9 kg.',
 ['Read current UAE agricultural-quarantine law definitions/scope and 2016 Cabinet personal-food announcement.','Cross-checked Japan MAFF postal manufactured-green-tea column, dated 21 April 2026.','Reviewed MOCCAE agricultural release service; its fresh-produce examples do not establish a processed-tea exemption.'])
add('BH','permit_required',
 'Permit/certificate route unless a processing exemption is confirmed: MAFF postal matrix BH=PQ*11. Bahrain NPPO requires phytosanitary certificates for regulated plants and plant products; current agricultural-quarantine service requires a pre-import licence. The traveller quantity exception does not establish a postal exception.',
 'Japan postal manufactured-tea matrix applies directly; Bahrain service expressly confines its small-quantity permit exception to plants accompanying travellers.',
 [M,'https://www.ippc.int/en/countries/bahrain/eventreporting/2017/10/import-phytosanitary-requirements-2/','https://www.mun.gov.bh/newportal/newportal/en/agriculture-marine-resources-affairs/services/examination-and-application-agricultural-quarantine','https://assets.ippc.int/static/media/files/eventreporting/2017/10/23/plant_quarantine_law_-_English.pdf'],
 'Obtain the Plant Protection and Quarantine decision on the finished-tea processing exemption or obtain the stated documents; confirm the personal food allowance separately. No verified numeric mailed-tea ceiling.',
 ['Read Bahrain NPPO phytosanitary notice and 2026 ministry service including traveller-only exemption.','Read GCC plant-product definition: manufactured products are covered when they present pest risk.','Current MAFF postal matrix supplies exact commodity/channel evidence. Bahrain food-guide PDF could not be freshly retrieved because of host certificate/connection failures; it is not used as agricultural clearance.'])
add('KW','permit_required',
 'Permit/certificate route unless a processing exemption is confirmed: MAFF postal matrix KW=PQ*11. PAFN Resolution 6/2023 Article 10 permits small personal-food consignments within authority-set quantities, with recipient name, residence, civil ID, food details and a written personal-use undertaking; inspection may apply. That food concession does not expressly waive plant quarantine.',
 'MAFF evidence is Japan postal manufactured green tea. PAFN Articles 8–10 concern non-commercial imported food and are not limited to accompanied baggage.',
 [M,'https://www.pafn.gov.kw/assets/images/Uploads/40118122204.pdf','https://assets.ippc.int/static/media/files/reportingobligation/2025/10/27/The_regulation_of_imported_food.pdf'],
 'Confirm the processing waiver with agricultural quarantine, otherwise obtain permit/certificate. PAFN must confirm a small personal quantity for this order; 24.9 kg is not established.',
 ['Read PAFN 2023 regulation Articles 8–10 and its NPPO-hosted copy, rather than superseded 2017 regulation.','Checked Kuwait IPPC reporting list, including the September 2026 update (its current entry has no downloadable text).','Cross-checked current MAFF postal product-specific route.'])
add('OM','permit_required',
 'Permit/certificate route unless a processing exemption is confirmed: MAFF postal matrix OM=PQ*11. Oman Customs publishes a plant-product import permit requiring phytosanitary and shipment/origin documents and inspection. The permit application precedes completion of the purchase order. The personal-import service preserves competent-authority permit requirements.',
 'MAFF expressly covers Japan postal tea. Oman personal-import rules require non-commercial quantities and preserve restrictions; no postal waiver was verified.',
 [M,'https://www.customs.gov.om/en/business-services/permit/permit-to-import-plant-products','https://customs.gov.om/en/import-of-goods-and-personal-effects/','https://micor.agriculture.gov.au/plants/oman_om/tea'],
 'Confirm the finished-tea processing waiver and actual permit requirement. Australian MICOR says certificate yes/permit no for Australian tea (NPPO verification 2013); it is not a Japanese-postal exemption and conflicts with the MAFF default. Resolve before dispatch.',
 ['Read Oman Customs permit and personal import services.','Cross-checked current Japan postal matrix against Australian MICOR exact processed-tea entry; retained the origin/date conflict.'])
add('QA','permit_required',
 'Permit/certificate route unless a processing exemption is confirmed: MAFF postal matrix QA=PQ*11. Qatar Agricultural Quarantine implementing rules define risk-bearing manufactured plant products and expressly apply quarantine to postal parcels. MOPH food-import guidance includes tea among assorted processed foods that can be covered by a food health certificate; that does not itself waive plant rules.',
 'Article 3 of the implementing regulation explicitly covers customs, post, travellers and other entry channels. Customs personal tax concessions do not waive agricultural requirements.',
 [M,'https://www.almeezan.qa/PrintArticle_section.aspx?LawTreeSectionID=12350&language=ar&lawId=3818','https://emsfsa.moph.gov.qa/en/moph_documents/guides%20and%20instructions/food%20importers%20guide.pdf'],
 'Obtain the Plant Protection Department decision on the finished-tea processing exemption, or permit and certificate, and determine the personal-food clearance procedure. No numeric personal postal tea allowance verified.',
 ['Read Qatar legal portal definitions and express postal scope.','Downloaded and read MOPH food importer guide, including separate processed-food/plant certificate templates and tea classification.','Cross-checked current MAFF postal manufactured-tea column.'])
add('SA','permit_required',
 'Permit/certificate route unless a processing exemption is confirmed: MAFF postal matrix SA=PQ*11. SFDA April 2025 clearance conditions expressly provide for personal-use food, requiring no local-market display and importer responsibility for safety. Those conditions do not expressly waive agricultural quarantine.',
 'MAFF concerns postal Japanese manufactured tea. SFDA personal-food clearance is a non-commercial shipment pathway, not solely a traveller allowance.',
 [M,'https://www.sfda.gov.sa/sites/default/files/2025-04/ConditionsRequirementsFoodClearanceE.pdf','https://micor.agriculture.gov.au/plants/saudi_arabia_sa/tea'],
 'Obtain MEWA confirmation of the processing exemption or arrange the applicable permit/certificate. MICOR gives certificate yes/permit no for Australian tea, with a 2015 NPPO verification date; do not transfer that permit exception to Japan post. Confirm SFDA accepts the actual quantity as personal.',
 ['Downloaded SFDA April 2025 guide and read page 10 personal-use subsection and tea table.','Cross-checked current MAFF Japan postal matrix and Australian MICOR processed-tea entry; recorded scope discrepancy.'])
add('JO','not_verified',
 'Jordan’s 2021 Plant Quarantine Instructions Article 3 covers designated plants/products and requires agricultural release at both public and private postal centres. Article 8 requires an original phytosanitary certificate for covered imports, with exemptions only for products separately designated by ministerial decision. A current designation covering or exempting manufactured sencha was not found.',
 'Postal scope is explicit. The personal-parcel JFDA guide found on Tawasal was a consultation; it is not treated as enacted clearance or a phytosanitary waiver.',
 ['https://moa.gov.jo/ebv4.0/root_storage/ar/eb_list_page/%D8%AA%D8%B9%D9%84%D9%8A%D9%85%D8%A7%D8%AA_%D8%A7%D9%84%D8%AD%D8%AC%D8%B1_%D8%A7%D9%84%D9%86%D8%A8%D8%A7%D8%AA%D9%8A_%D9%84%D8%B3%D9%86%D8%A9_2021.pdf','https://tawasal.gov.jo/Consultations/Public/1436/Guideline_for_the_Import_of_Personal_Parcels'],
 'Ministry of Agriculture must classify finished steamed/dried green tea under the implementing commodity decisions and confirm postal certificate/permit requirements; JFDA must identify the enacted personal-food procedure.',
 ['Read ministry’s 2021 instructions, Articles 3 and 8, including public/private post.','Searched ministry tea certificate/exemption decisions in Arabic and English and JFDA personal-parcel guidance; no enacted finished-tea postal exemption identified.'])
add('LB','not_verified',
 'Law 778/2006 Article 2 covers manufactured plant products when their processing/nature can carry pest risk. Article 4 expressly subjects postal imports to agricultural release; Article 9 requires phytosanitary certification for covered imports. The ministry’s March 2026 emergency measure accepts copies temporarily with a notarised undertaking to supply originals; it does not waive certification or resolve finished-tea classification.',
 'Law 778 Article 4 explicitly includes public/private post and traveller consignments. No personal-use exemption for processed Japanese tea was established.',
 ['https://regulations.agriculture.gov.lb/Backoffice-mvc/API/File/Law%20778_20220819115205.pdf','https://regulations.agriculture.gov.lb/en','https://www.agriculture.gov.lb/Media/News/2026/%D9%88%D8%B2%D8%A7%D8%B1%D8%A9-%D8%A7%D9%84%D8%B2%D8%B1%D8%A7%D8%B9%D8%A9-%D8%AA%D8%B9%D8%AA%D9%85%D8%AF-%D8%AA%D8%AF%D8%A7%D8%A8%D9%8A%D8%B1-%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7%D9%8A%D9%8A%D8%A9-%D9%84%D8%AA%D8%B3%D8%B1%D9%8A%D8%B9-%D8%A7%D8%B3%D8%AA%D9%8A%D8%B1%D8%A7'],
 'Obtain the ministry’s HS090210 finished-tea classification and any personal postal exemption or required certificate. Confirm the receiving postal service’s separate permission rules before dispatch.',
 ['Read current ministry-hosted Law 778 definitions, postal scope and certificate provisions.','Checked ministry product portal (green tea listed) and 14 March 2026 temporary certificate-copy measure; neither establishes personal finished-tea exemption.'])
add('IQ','not_verified',
 'Agricultural Quarantine Law 76/2012, consolidated with 2020 amendments, Article 7 requires an import licence and phytosanitary certificate for regulated products. Article 9 exempts non-agricultural-purpose consignments sent by mail, carried or shipped, up to 10 kg, from the certificate; border examination remains. The exemption does not expressly remove the Article 7 import licence. Finished tea’s licensing classification was not established.',
 'The 10 kg certificate exemption explicitly includes mail and commodities not intended for agricultural purposes. Applying that class to drinking tea is an inference; it does not establish an unrestricted postal route.',
 ['https://www.moj.gov.iq/upload/pdf/%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D8%AD%D8%AC%D8%B1%20%D8%A7%D9%84%D8%B2%D8%B1%D8%A7%D8%B9%D9%8A.pdf','https://pflanzengesundheit.julius-kuehn.de/dokumente/upload/iq_2012-76cons2020_pqact_en.pdf'],
 'Confirm that the 10 kg non-agricultural-use exemption covers this sencha and whether an import licence remains required. The law does not define the 10 kg weight basis. Current 24.9 kg net exceeds the exemption under either net or gross interpretation.',
 ['Read Iraqi Justice Ministry English consolidated law Articles 1, 7 and 9 and 2020 amendment references.','Cross-checked independent German NPPO consolidated translation of Article 9.','Searched for tea-specific agricultural import designation; postal tea composition rules alone do not answer it.'],
 dict(netGrams=10000,inclusive=True,kind='conditional certificate-exemption threshold',scope='Only if non-agricultural-purpose classification is confirmed; import licence question remains',weightBasisCaveat='Law says weight of materials, without expressly defining net or gross.'))
(p/'asia-gulf.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
print(len(rows),'saved')
