import json,pathlib
p=pathlib.Path('docs/reports/tea-audit-work/europe.json');rows=json.loads(p.read_text());names={r['code']:r['name'] for r in json.load(open('docs/reports/tea-shipping-audit-2026-09-29.json'))['destinations']}
def add(code,status,rule,mail,authority,urls,limit=None,question=None,attempts=None):
 global rows
 rows=[r for r in rows if r['code']!=code]
 rows.append(dict(code=code,name=names[code],status=status,rule=rule,personalMailApplicability=mail,quantityLimit=limit,authority=authority,evidenceUrls=urls,remainingQuestion=question,researchAttempts=attempts or ['Read the authority’s product and personal-use guidance and separated postal applicability from passenger-only allowances.'],reviewedAt='2026-09-29'))
def save():p.write_text(json.dumps(sorted(rows,key=lambda x:x['code']),ensure_ascii=False,indent=2)+'\n')
add('NO','allowed','Plain tea is expressly included among non-animal foods allowed from outside the EU/EEA for the recipient’s own consumption. No agricultural tea-weight limit is stated.','The same page explicitly permits receiving these goods as parcels; resale is excluded.','Norwegian Food Safety Authority',['https://mattilsynet.no/import/import-av-mat/ta-med-mat-og-drikke/privat-import-av-mat-utenfor-eu-eos'])
add('FO','allowed','TAKS expressly permits food ordered online by private individuals; doubtful consignments go to the Faroese Food and Veterinary Authority. No tea-specific agricultural permit or quantity restriction is stated.','Official guidance specifically addresses foreign online purchases delivered as parcels.','TAKS / Faroese Food and Veterinary Authority',['https://www.taks.fo/en/individuals/customs/online-shopping'])
add('IS','conditional','Vegan foods for personal consumption are permitted. Use unopened labelled consumer packaging with an ingredients list. MAST states a less-than-30 kg small personal quantity for non-animal foods from third countries.','The page expressly covers online purchases, gifts by post and luggage; the 30 kg paragraph begins with passengers but the following small-personal-consumption exception is general. Keep postal consignments below 30 kg.','Icelandic Food and Veterinary Authority (MAST)',['https://www.mast.is/en/import-export/what-can-i-bring-with-me-to-iceland','https://www.mast.is/en/import-export/import-of-plants'],{'netGrams':30000,'inclusive':False,'basis':'MAST small personal non-animal food allowance; stay below 30 kg','scope':'personal consignment'},'The 30 kg guidance is phrased in the passenger subsection as well as the general personal-use exception; no larger postal allowance is asserted.')
add('GB','allowed','Processed packaged plant products may enter Great Britain without a phytosanitary certificate; plain steamed/dried sencha meets that description. Northern Ireland applies the EU dried-tea exemption.','The UK plant-import overview explicitly covers personal goods ordered by post. The processed-product exemption is commodity-based, not a weight allowance for baggage.','Defra; DAERA Northern Ireland',['https://www.gov.uk/bringing-plants-and-wood-into-great-britain','https://www.gov.uk/bringing-food-into-great-britain/fruit-vegetables-nuts-seeds','https://www.daera-ni.gov.uk/articles/summary-personal-food-import-restrictions'])
add('IM','allowed','The Isle of Man applies UK import guidance and retained EU plant-health regulations; processed packaged tea falls outside fresh living plant controls.','Manx Customs expressly applies UK guidance to direct imports; plant-health requirements apply by product, including mail.','Isle of Man Customs and DEFA',['https://www.gov.im/categories/tax-vat-and-your-money/customs-and-excise/imports-and-exports/','https://www.legislation.gov.im/cms/images/LEGISLATION/SUBORDINATE/2023/2023-0152/2023-0152.pdf','https://www.gov.uk/bringing-food-into-great-britain/fruit-vegetables-nuts-seeds'])
add('JE','allowed','Jersey’s current legislation incorporates Regulations 2016/2031 and 2019/2072, whose fresh/living tea-leaf controls do not cover finished dried tea. No separate dried-tea quarantine requirement was found in the Jersey modifications.','Jersey’s legislation governs imports generally. Its postal plant-passport warnings concern regulated plants, not finished dried tea.','Jersey Plant Health Inspectorate; Jersey Law',['https://www.jerseylaw.je/laws/current/ro_20_2020','https://www.jerseylaw.je/laws/current/l_30_2003_20210927','https://www.gov.je/Industry/FarmingFishing/PlantsProduce/Pages/ImportExport.aspx'])
save()
