exec(open('docs/reports/tea-audit-work/europe-add.py').read())
add('GG','allowed','Legal classification inference: the preserved plant-health import schedule regulates only fresh, whole, uncut, unfermented tea leaves under ex090210/ex090220. Steamed and dried retail sencha is outside that described commodity; no phytosanitary certificate requirement was identified for the finished tea.','The preserved legislation governs imports generally; this conclusion does not rely on a passenger allowance.','States of Guernsey preserved plant-health legislation; German NPPO consolidated copies',['https://pflanzengesundheit.julius-kuehn.de/regelungen-guernsey-jersey-insel-man.html','https://pflanzengesundheit.julius-kuehn.de/dokumente/upload/gg_eu2019-2072cons2024-73_PhytoCond.pdf','https://pflanzengesundheit.julius-kuehn.de/dokumente/upload/gg_eu2016-2031cons2023-41_PHO-jki.pdf'],attempts=['Read retained regulation Annex11 PartB, p359/363: fresh tea only; checked JKI current Guernsey legislation index.'])
add('MK','allowed','Legal classification inference: ListV PartB specifies fresh, whole, uncut and unfermented tea leaves under ex090210/ex090220. Manufactured steamed/dried sencha falls outside that regulated description and no phytosanitary certificate requirement was found for it.','The NPPO list governs all imported consignments, including post; no passenger exemption is used.','North Macedonia NPPO legislation filed with the IPPC',['https://assets.ippc.int/static/media/files/reportingobligation/2022/04/13/Lists__eng.pdf'],attempts=['Read ListV PartB subsectionB3 and tea entry on printed p153; distinguished fresh tea leaves from processed sencha.'])
add('ME','allowed','Legal classification inference from the March2026 plant-health schedule: certificate-controlled tea is fresh, whole, uncut and unfermented tea leaves, not manufactured steamed/dried sencha. The English and German official translations make the fresh limitation explicit.','The import schedule applies generally, rather than creating a baggage-only exemption.','Montenegro Ministry of Agriculture/UBHVFP; German NPPO translation',['https://www.gov.me/clanak/propisi-iz-oblasti-zdravstvene-zastite-bilja','https://wapi.gov.me/download/d8cf5c3b-65cc-446f-a3a3-a2052b4c95cc?version=1.0','https://pflanzengesundheit.julius-kuehn.de/dokumente/upload/me_2026-41_qso-anf_de.pdf','https://wapi.gov.me/download/9179cb31-2b87-4864-82ed-c4dec5131471?version=1.0'],attempts=['Downloaded the March24,2026 current schedule, checked ex090210/ex090220 and JKI German translation p236, and compared official English schedule.'])
add('MD','conditional','Decision938/2018 Annex5 permits personal, non-commercial plant-product consignments up to5kg without a phytosanitary certificate, excluding seeds and planting material. Plain dried sencha fits the non-propagating plant-product scope; quarantine inspection can still occur.','Annex5 expressly includes small consignments ordered at a distance and delivered to consumers through postal services.','Moldova Government Decision938/2018 Annex5; Moldovan Post',['https://bwcimplementation.org/sites/default/files/resource/MD_Decision%20No.%20938%20of%202018_ANNEX%205_RO.pdf','https://bwcimplementation.org/sites/default/files/resource/MD_Decision%20No.%20938%20of%202018_ANNEX%205_EN.pdf','https://static-api.posta.md/api/v1/storage/26/01/2023/Republica_Moldova_OI_rBt0fsI.pdf'],limit={'netGrams':5000,'inclusive':True,'scope':'Personal plant-product consignment; phytosanitary certificate exemption, not a carrier or tax allowance.'},attempts=['Compared Romanian law text and English translation, Annex5 paragraphs1 and5; checked Moldovan Post reference to Decision938.'])
add('SM','allowed','Legal inference: San Marino applies Union phytosanitary legislation under its customs/cooperation agreement and Decision1/2010. Under that regime, manufactured dried tea is exempt from phytosanitary certification; the EU fresh-leaf control does not apply to steamed/dried sencha.','Decision1/2010 concerns import legislation generally. The EU private-order guidance expressly covers goods ordered from abroad, rather than only carried in luggage.','EU-San Marino Cooperation Committee; European Commission; Swedish NPPO',['https://eur-lex.europa.eu/eli/dec/2010/1%284%29/oj/eng','https://food.ec.europa.eu/horizontal-topics/international-affairs/eu-entry-conditions/sanitary-and-phytosanitary-agreements_en','https://jordbruksverket.se/languages/english/swedish-board-of-agriculture/plants/bringing-in-or-ordering-plants-and-plant-products-to-sweden-as-a-private-individual'],attempts=['Read Decision1/2010 recitals6 and Articles4–5 applying Union phytosanitary legislation; applied the verified dried-tea commodity exemption.'])
# Replace obsolete Jersey historical consolidation reference; current implementing orders already provide the operative evidence.
for r in rows:
 if r['code']=='JE': r['evidenceUrls']=[u for u in r['evidenceUrls'] if 'l_30_2003_20210927' not in u]
save()
print('Saved',len(rows),'rows')
