import json,pathlib
p=pathlib.Path(__file__).with_name('americas.json')
a=json.loads(p.read_text()); rows={r['code']:r for r in a}
def setrow(code,status,rule,scope,authority,urls,question='',limit=None,attempts=None):
 r=rows[code];r.update(status=status,rule=rule,personalMailApplicability=scope,quantityLimit=limit,authority=authority,evidenceUrls=urls,remainingQuestion=question,researchAttempts=attempts or ['Checked destination authority agricultural guidance, processed-tea classification and personal/postal applicability.'])
def save():p.write_text(json.dumps(list(rows.values()),indent=2,ensure_ascii=False)+'\n')
setrow('US','allowed','APHIS expressly lists dried Camellia sinensis tea among generally admissible plant products needing no plant import permit or other APHIS requirements. Retain clear ingredients and origin labels.','General commodity import rule covers mail; does not rely on traveler baggage exemption. FDA food prior notice remains a separate requirement.','USDA APHIS',['https://www.aphis.usda.gov/ace/generally-authorized-non-propagative-plant-products'])
setrow('CA','conditional','CFIA permits tea from countries other than the US without additional restrictions within the personal-use maximum of 20 kg.','CFIA explicitly applies this guidance to online purchases as well as travelers.','Canadian Food Inspection Agency',['https://inspection.canada.ca/en/food-safety-consumers/bring-food-personal-use','https://inspection.canada.ca/en/about-cfia/acts-and-regulations/list-acts-and-regulations/documents-incorporated-reference/personal-use-exemption'],limit={'netKg':20,'max100gBags':200,'basis':'Per person per shipment; combined category limit, solely personal use.'})
setrow('BR','conditional','MAPA category 1 includes dehydrated plants and plant parts; no phytosanitary authorization or certificate, but inspection at entry. Sealed manufactured sencha fits this processing category.','General import commodity classification applies to postal consignments, not merely baggage; personal quantity must remain consistent with use.','Brazil MAPA',['https://www.gov.br/agricultura/pt-br/assuntos/sanidade-animal-e-vegetal/sanidade-vegetal/analise-de-riscos-de-pragas','https://www.gov.br/agricultura/pt-br/assuntos/sanidade-animal-e-vegetal/sanidade-vegetal/ListadeProdutosdeCategoriadeRisco124.4.2025.docx.pdf'])
setrow('AG','not_verified','Antigua requires permits and phytosanitary certificates for regulated plants, including some processed foods, in any quantity. Its published processing examples do not classify heat-processed retail Camellia tea.','All inbound consignments covered if regulated; no established small postal exemption.','Antigua and Barbuda Plant Protection Unit',['https://agriculture.gov.ag/index.php/plant-protection/','https://agriculture.gov.ag/wp-content/uploads/2022/06/Import-Status-of-Plant-Commodities-and-Regulated-Items-PLANT-PROTECTION-ANTIGUA-AND-BARBUDA-ver.-27082020.pdf'],'Does the NPPO classify sealed steamed/dried sencha as regulated or sufficiently processed?')
setrow('KN','not_verified','Government guidance requires prior permits for unprocessed plant products and certificates/inspection for permitted small quantities. Its explicit dried-tea example is for exports, so it cannot establish an import requirement or exemption for sencha.','General public included, but postal finished-tea classification unresolved.','St Kitts and Nevis Department of Agriculture',['https://www.sknis.gov.kn/2020/06/26/plant-and-plant-product-import-requirements/'],'Confirm processed tea import category and any personal-post permit/certificate exemption.')
setrow('TT','not_verified','The ministry expressly applies plant permit and phytosanitary certificate controls to online and postal purchases. Regulations allow pest-safe preserved fruits/vegetables, but neither text resolves whether finished Camellia tea is outside regulated plant products.','Mail and courier explicitly covered for regulated products.','Trinidad and Tobago Plant Quarantine Service',['https://agriculture.gov.tt/media-releases/what-you-need-to-know-about-a-plant-import-permit/','https://www.ttbizlink.gov.tt/trade/tnt/cmn/pdf/Plant%20Protection%20Subsidiary%20Regulations-63.56.pdf'],'Obtain exact processed-tea classification; do not equate a raw-leaf permit rule with manufactured tea.')
setrow('BZ','permit_required','BAHA provides a processed-food import permit application explicitly covering personal consumption and mail/courier. Obtain BAHA clearance for the exact Japanese tea before shipment; additional plant certification depends on the issued conditions.','Personal consumption and Mail are express options on the 2025 form.','Belize Agricultural Health Authority',['https://baha.org.bz/food-safety/','https://baha.org.bz/wp-content/uploads/2025/04/FS-Permit.pdf'],'BAHA must specify any tea-specific plant certificate conditions; no automatic personal-use exemption located.')
setrow('AW','not_verified','Aruba food-import guidance lists tea for an economic import licence; this does not establish the agricultural treatment of small personal postal purchases.','Personal postal exemption and exact finished-tea agricultural classification not stated.','Aruba import requirements, reproduced by Germany JKI',['https://pflanzengesundheit.julius-kuehn.de/dokumente/upload/aw_2022_imp-req_en.pdf'],'Clarify personal postal tea licence scope and whether processed tea needs plant-health documentation.')
setrow('CW','not_verified','Curaçao customs requires permits for plants and flowers but does not classify manufactured dried tea. Personal goods customs clearance alone is insufficient agricultural evidence.','Traveler page and general import procedure reviewed; no tea-specific postal provision found.','Douane Curaçao',['https://douane.cw/particulier/reizigersbagage/verboden-in-en-uit-te-voeren/','https://douane.cw/zakelijk/inklaring-en-invoer/'],'Confirm agriculture exemption or requirements for commercially sealed Japanese tea sent by post.')
setrow('BQ','not_verified','Bonaire permits dried herbs under a specific Venezuela reopening measure; that is not a Japan-wide tea rule and does not establish Saba or Sint Eustatius conditions.','Country code covers three islands with unresolved personal-mail plant-health application.','Public Entity Bonaire',['https://bonairegov.com/en/nieuwsoverzicht/artikel/import-uit-venezuela-versoepeld'],'Verify Japanese processed tea for each of Bonaire, Saba and Sint Eustatius; do not apply EU or Venezuela-only rules.')
setrow('SX','not_verified','Sint Maarten LVV regulates imports of plants and plant produce; its published plant form does not settle manufactured tea or a personal exemption.','No affirmative postal processed-tea rule found.','Government of Sint Maarten LVV',['https://www.sintmaartengov.org/Ministries/Departments/Pages/Agriculture-Livestock-and-Fisheries.aspx','https://www.newgmc.com/index.php?download=466%3Aproduce-and-plant-produce-import-form&id=35%3Asops-a-ssops&option=com_phocadownload&view=category'],'Confirm whether sencha is regulated and whether certificates or permits apply to personal parcels.')
save()
setrow('KY','conditional','Department of Agriculture explicitly allows commercially packaged processed tea and coffee. Declare all food to Customs for agricultural inspection.','The commodity FAQ covers imports generally, rather than a baggage-only concession.','Cayman Islands Department of Agriculture',['https://doa.gov.ky/faqs/','https://doa.gov.ky/service/agricultural-health-inspection-services/'])
setrow('FK','conditional','Processed plant materials are permitted in sealed packaging identifying product, processing method, manufacturer and origin. Tea must be clean, manufactured and labelled; biosecurity can inspect.','General importer guidance applies to consignments. Passenger allowances are not used as parcel allowances.','Falkland Islands Department of Agriculture Biosecurity',['https://www.gov.fk/agriculture/wp-content/uploads/sites/28/2026/03/Importers-Guide-2020.pdf','https://www.gov.fk/agriculture/biosecurity/importing-exporting/'])
setrow('GU','not_verified','Guam regulation 10120 permits stored dried human foods subject to inspection and freedom from storage pests. Sections 10101 and 10103 separately require permits for regulated plant products; the text does not expressly say whether manufactured sencha needs that permit.','Territorial import rule covers shipments, not just passengers. Federal mainland tea rules cannot settle Guam permit interpretation.','Guam Department of Agriculture and Compiler of Laws',['https://www.guamcourts.org/compileroflaws/GAR/08GAR/08GAR002-10.pdf','https://doag.guam.gov/biosecurity-division/'],'Confirm whether sealed heat-processed dried tea under 10120 is non-regulated and permit-exempt.')
setrow('MP','not_verified','CNMI section 85-60.2-238 allows stored dried human food, subject to inspection and pest freedom. Sections 201/204 distinguish non-regulated goods from plant products needing permits; section 202 does not list dried foods for phytosanitary certificates.','CNMI Customs controls incoming US Postal Service goods; the dried-food entry rule is not baggage-only.','CNMI Law Revision Commission; Customs and Quarantine',['https://cnmilaw.gov/docs/admincode/T85/T85-60.2.pdf','https://www.finance.gov.mp/customs-quarantine.php'],'Confirm dried manufactured tea is a non-regulated food for permit purposes under sections 201/204/238.')
setrow('AS','permit_required','American Samoa plant quarantine rules require a prior permit for plant material, with origin certification and arrival inspection; definitions include plant products and no manufactured-tea exception was identified. Obtain the tea-specific permit before dispatch.','Import definition covers any person and shipment. No small personal postal waiver found.','American Samoa plant quarantine regulations, chapter 24.03',['https://faolex.fao.org/docs/pdf/ams68618.pdf','https://asbar.org/regulation/24-0328-permit-for-plant-material-importation/'],'Agriculture must confirm permit conditions and the required origin certificate for sealed Japanese sencha.')
setrow('NI','not_verified','NTON 11003, published January 2024, expressly covers all quantities, presentations, online purchases and postal consignments. Regulated consignments require importer registration, import permit and phytosanitary documentation. A finished-tea classification or processing exemption was not established.','Personal postal purchases expressly within the new standard; do not rely on the superseded 11005-08 rule.','Nicaragua IPSA',['https://www.ipsa.gob.ni/Portals/0/5%20Cuarentena%20Agropecuaria/Normas%20y%20procedimientos/Gaceta%2015.07.2024%20NTON%2011003.pdf'],'Does IPSA regard factory-steamed/dried Camellia tea as a regulated consignment requiring the NTON permit procedure?')
setrow('AR','not_verified','SENASA applies AFIDI plant requirements to regulated commercial and noncommercial consignments. Personal online food customs/ANMAT simplification does not determine whether this sencha is phytosanitary category 1 or 2.','Noncommercial consignments are expressly covered by SENASA; personal postal food rules must not be treated as plant-health clearance.','Argentina SENASA',['https://www.argentina.gob.ar/node/102592','https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-12-2021-346384/actualizacion','https://www.argentina.gob.ar/node/455690'],'Confirm sencha processing category and whether a SENASA import request/AFIDI is required for a personal parcel.')
rows['CA']['quantityLimit']={'netGrams':20000,'max100gBags':200,'inclusive':True,'scope':'Per person per shipment; aggregate tea category, solely personal use.','kind':'personal-use limit'}
save()
setrow('PE','conditional','SENASA classifies loose green tea in retail packs of 3 kg or less (0902.10.00.00 P2) as phytosanitary risk category 2. Postal procedure 6.2.1 waives import permit and origin phytosanitary certificate, but requires inspection on arrival. A 100 g loose-leaf pouch is not the category-1 tea-filter/capsule exemption.','The official procedure is expressly for postal consignments. The 3 kg threshold describes immediate packaging for tariff classification, not a total personal allowance.','Peru SENASA',['https://www.senasa.gob.pe/senasa/descargasarchivos/2017/08/Listado-mercancias-agrarias-reguladas-09.12.2020.pdf','https://www.senasa.gob.pe/senasa/descargasarchivos/2014/11/49.pdf','https://www.senasa.gob.pe/senasa/descargasarchivos/2015/02/12.pdf'],'The July 2026 list landing page could not be retrieved; latest accessible detailed list and standing postal procedure agree on CRF2 treatment.')
setrow('UY','allowed','MGAP public database lists PRODUCTOS VEGETALES ACONDICIONADOS AL DETALLE, explicitly including tea, among products without entry controls. Sealed 100 g retail sencha matches that commodity; do not extend this conclusion to bulk raw leaves.','The entry-control exemption is a general commodity classification, not a traveler allowance.','Uruguay MGAP DGSA',['https://www.mgap.gub.uy/consultaRequisitos/requisitosincontrol.aspx','https://www.gub.uy/ministerio-ganaderia-agricultura-pesca/tramites-y-servicios/servicios/consulta-requisitos-para-ingreso-productos-vegetales'],attempts=['Opened MGAP public no-control database; extracted current embedded result row 4047 / PVDET19999100 expressly listing retail tea.'])
setrow('BS','not_verified','BAHFSA explicitly lists tea for agricultural declaration/inspection. Its general plant rules require permit and phytosanitary certificate, including mail/courier. Guidance does not resolve whether sealed industrially processed tea is exempt from the raw/minimally processed category.','Mail, couriers and freight forwarders expressly covered by plant rules; traveler tea declaration is not proof of a postal permit waiver.','Bahamas Agricultural Health and Food Safety Authority',['https://bahfsabahamas.com/sectors/plants/faqs','https://bahfsabahamas.com/sectors/international/guidelines-for-the-importation-of-plants-and-plant-products','https://bahfsabahamas.com/downloads/documents/legislation/Food-Import-Conditions-Appendix.pdf'],'Ask BAHFSA whether manufactured tea requires the individual permit and phytosanitary certificate; do not ship under a presumed small-quantity exemption.')
setrow('BB','not_verified','Barbados provides a plant import-permit procedure, including personal consumption and mail selections. Plant regulation applicability to sufficiently processed manufactured tea was not determined; a draft replacement Act is not treated as enacted law.','Personal/mail options establish that individual parcels can be regulated; they do not prove that sencha is regulated or exempt.','Barbados Ministry of Agriculture Plant Quarantine',['https://agriculture.gov.bb/Apply/ImportationOfPlants'],'Confirm finished Camellia tea classification under the operative Plant Protection Act and any permit/certificate exemption.')
setrow('JM','not_verified','Jamaica plant quarantine guidance provides permits, original phytosanitary documentation and inspection for regulated plant products, with a personal JSWIFT application route. No tea-specific processed-product exemption was verified.','Personal import route identified; no evidence that a baggage concession exempts commercial mail purchases.','Jamaica Ministry of Agriculture Plant Quarantine',['https://www.moa.gov.jm/sites/default/files/Import-Requirement-and-Permit-Application-Process.pdf','https://www.moa.gov.jm/sites/default/files/Import%20Process%20BROCHURE.pdf'],'Obtain PQPI classification and any Japanese sencha permit requirements; website commodity table could not be retrieved.')
setrow('LC','not_verified','Saint Lucia regulates processed or unprocessed vegetable-origin articles capable of carrying pests. Regulation 16 requires permits and regulation 12 expressly covers mail. Sealed heat-processed tea is not specifically classified in published guidance.','Mail is expressly subject to the plant regulations; no personal parcel exemption established.','Saint Lucia Attorney General and Plant Quarantine',['https://attorneygeneralchambers.com/laws-of-saint-lucia/plant-protection-act/section-2-02','https://attorneygeneralchambers.com/laws-of-saint-lucia/plant-protection-act/section-16-01','https://attorneygeneralchambers.com/laws-of-saint-lucia/plant-protection-act/section-12'],'Does the authority consider manufactured dried sencha capable of carrying pests, and thus a regulated plant product?')
save()
setrow('PA','conditional','Panama Resolution 055-2016 admits commercially manufactured, labelled dehydrated plant parts without plant-health certification. Personal mail requires an approved online personal-consumption notification, ID and invoice before entry. Maximum 5 kg per person or 10 kg per family; no more than three postal/courier notifications yearly.','Article 6 explicitly covers private or public messaging/postal services, and applies the weight caps to both travelers and such shipments.','Panama Agencia Panameña de Alimentos',['https://sit.apa.gob.pa/aupsa/requisitos/RES055_2016MuestraConsumoPersonalEventosDonacionesTODOS.pdf','https://sit.apa.gob.pa/ConsumoPersonal/login.aspx?AspxAutoDetectCookieSupport=1','https://apa.gob.pa/la-apa-te-informa-sobre-los-alimentos-que-pueden-ingresar-losviajeros-a-traves-del-aeropuerto-internacional-de-tocumen/'],limit={'netGrams':5000,'inclusive':True,'max100gBags':50,'scope':'All personal food in a consignment per person; 10000 g per family; no more than 3 postal/courier notifications per year.','kind':'personal food exemption limit'})
setrow('PY','permit_required','SENAVE explicitly distinguishes retail-packed tea for direct consumption (risk category 1) from bulk dried tea (category 2). Category 1 avoids category-2 AFIDI/phyto requirements but still requires prior import authorization through VUI under the published sanctions schedule.','General import requirement is not limited to commercial resale; no personal postal exemption verified.','Paraguay SENAVE',['https://www.senave.gov.py/documentos/resoluciones/6902467e5fc82a2f6c338fd335bf3ff9.pdf','https://www.senave.gov.py/documentos/resoluciones/25dc78257a43b42519e9b47871d61090.pdf'],'Confirm how an individual obtains category-1 VUI authorization for a small postal purchase; do not demand bulk-tea AFIDI by default.')
setrow('EC','conditional','Andean Resolution 1475 lists retail green tea as risk category 2; the default is no import permit or phytosanitary export certificate, with arrival inspection. National product-specific exceptions can override this general rule. Declare manufactured tea accurately and retain processing/origin details.','Resolution expressly covers trade with third countries, not only Andean trade or passenger baggage; therefore relevant to Japanese postal parcels.','Ecuador Agrocalidad / Andean Community',['https://www.agrocalidad.gob.ec/wp-content/uploads/2020/05/fito30.pdf','https://www.agrocalidad.gob.ec/direccion-de-control-fitosanitario/'],'No Japan-sencha-specific national exception was located; confirm the commodity entry with Agrocalidad before operational rollout.')
setrow('CR','not_verified','Costa Rica requires plant-health clearance for regulated NT35 goods. The public requirement database distinguishes processed leaves, dried leaves and tea infusions, but Japan queries failed and did not establish which requirements apply to this retail product.','No personal-post exemption established; commodity classification must precede any permit requirement.','Costa Rica Servicio Fitosanitario del Estado',['https://www.sfe.go.cr/SitePages/Tramites/tramites_importacion_vegetales.aspx','https://app.sfe.go.cr/SFECuarentena/aspx/RequisitosImportacion/ConsultarRequisitosImportacion.aspx'],'Obtain the Japan/Camellia sinensis/processed-leaf commodity result and clarify NT35 scope.',attempts=['Read import guidance and current public query form. Attempted Japan processed-leaf and dry-leaf searches; server returned unspecified system errors.'])
setrow('DM','not_verified','Dominica plant import guidance requires prior permission, export phytosanitary certification and inspection for regulated plant material. The Act exempts certain preserved fruits/vegetables but does not specifically classify manufactured Camellia tea.','Individual import procedure exists; no personal postal tea exemption established.','Dominica Ministry of Agriculture',['https://establishment.gov.dm/services/application-import-permit','https://divisionofagriculture.gov.dm/images/documents/forms/sample_import_permit_and_submission_form.pdf','https://faolex.fao.org/docs/pdf/dmi4119.pdf'],'Confirm whether heat-processed retail sencha is regulated and requires permit/phyto for postal entry.')
setrow('GD','not_verified','Grenada plant controls require permits and plant-health certification for regulated plant products. Published import summaries did not establish that fully manufactured sencha falls within that category or has a personal-mail exemption.','No affirmative postal tea allowance verified; tariff availability does not establish plant-health clearance.','Grenada Ministry of Agriculture; government-notified WTO trade policy review',['https://www.wto.org/english/tratop_e/tpr_e/s299-02_e.pdf','https://www.ippc.int/en/countries/grenada/'],'Obtain NPPO ruling on manufactured Japanese tea and personal postal permit/certificate requirements.')
setrow('VC','not_verified','The 2015 Plant Protection Act provides for interception of plant consignments by the postal corporation and private postal providers. Import licensing applies to regulated plant products; no tea-specific manufacturing exemption was verified.','Postal channels expressly covered by section 15; no personal quantity exception established for this tea.','St Vincent and the Grenadines Plant Protection and Quarantine',['https://faolex.fao.org/docs/pdf/stv160536.pdf','https://importlicensing.wto.org/content/plant-and-plant-products-2'],'Confirm whether factory-steamed/dried tea is regulated and the exact personal postal permit/certificate conditions.')
setrow('MS','not_verified','Montserrat Plant Protection Act controls regulated plants and products; its preserved-fruit exceptions do not expressly settle processed tea. The government confirms current agricultural permit administration following 2025 amendments, which concern citrus rather than tea.','No manufactured-tea exemption for individual post found in law or current guidance.','Montserrat Department of Agriculture',['https://faolex.fao.org/docs/pdf/msr98141.pdf','https://www.gov.ms/2025/03/07/citrus-fruits-now-allowed-for-importation-to-montserrat/'],'Confirm finished tea classification, permit/certificate requirements and any personal-post exemption.')
setrow('TC','not_verified','Turks and Caicos requires permits for regulated plant articles; only fruits/vegetables have the published 25 lb threshold. Manufactured tea is not classified in that guidance, so neither blanket permit necessity nor exemption is proven.','General individual/company imports covered; do not apply the 25 lb produce threshold to tea or invent a postal exemption.','Turks and Caicos Department of Agriculture',['https://gov.tc/trade/portal/imports','https://www.agriculture.gov.tc/residents'],'Does commercially sealed heat-processed sencha fall outside regulated articles; if not, which permit/certificate conditions apply?')
save()
setrow('MX','allowed','Japan Plant Protection Station explicitly lists manufactured green tea as admissible to Mexico by post without Japanese phytosanitary export inspection or certificate (postal table, 21 April 2026, ◎). This covers finished tea, not fresh leaves or herbal mixtures.','The source is explicitly the postal table, independently corroborated by the Mexico cargo table. No personal tea weight limit appears in that agricultural guidance.','Japan MAFF Plant Protection Station, reporting Mexican plant import requirements',['https://www.maff.go.jp/pps/j/search/e_hayami_yubin.pdf','https://www.maff.go.jp/pps/j/search/ekuni/sa/mexico/kamotsu.html'],attempts=['Read the current Japanese NPPO postal table and Mexico manufactured-green-tea cargo entry; searched SENASICA guidance without locating an equally specific personal-mail tea entry.'])
for code in ['PR','VI']:
 setrow(code,'allowed','APHIS expressly authorizes dried Camellia sinensis tea without plant import permit or phytosanitary certificate; all consignments remain subject to arrival inspection. Current 7 CFR 319.7 expressly includes Puerto Rico and the US Virgin Islands within the United States for these import provisions.','The general commodity authorization is not a baggage concession. The regulatory movement definition expressly includes mail. No tea-specific agricultural weight ceiling found.','USDA APHIS; eCFR 7 CFR 319.7',['https://www.aphis.usda.gov/ace/generally-authorized-non-propagative-plant-products','https://www.ecfr.gov/current/title-7/subtitle-B/chapter-III/part-319/subpart-D/section-319.7'],attempts=['Checked the APHIS Camellia tea authorization and the current regulatory territorial and mail definitions; did not infer applicability solely from US affiliation.'])
setrow('CL','not_verified','SAG Resolution 1284/2021 puts dried AND crushed tea in risk category 1. The product here is steamed and rolled loose leaves, so the listed crushing/fermentation treatment cannot simply be assumed. Higher risk categories can require phytosanitary documentation.','The processing categories apply to imports generally; no baggage allowance is used as postal clearance.','Chile SAG',['https://www.sag.gob.cl/ambitos-de-accion/categorias-de-riesgo-fitosanitario','https://www.sag.gob.cl/sites/default/files/res._1.284_de_2021_con_anexo.pdf','https://www.maff.go.jp/pps/j/search/ekuni/sa/chile/index.html'],'Does steamed, rolled but not deliberately crushed sencha meet category 1 through its heat treatment, or require category 2 certification?',attempts=['Read the SAG risk-category rule and its tea processing entry; cross-checked March 2026 Japanese NPPO Chile requirements. Identified the unproven dried-and-crushed versus whole sencha distinction.'])
setrow('DO','not_verified','Dominican plant quarantine applies prior authorization and phytosanitary controls to regulated vegetable products. The 2025 VUCE exclusion and inspection-release lists do not establish an exemption for retail green tea under 090210.','The passenger personal-use protocol is not extended to individual postal purchases.','Dominican Republic Ministry of Agriculture; VUCE',['https://agricultura.gob.do/servicios/informacion-sobre-procedimientos-para-la-importacion-de-productos-y-sub-productos-de-origen-vegetal/','https://vucerd.gob.do/media/2219/exclusi%C3%B3n-de-subpartidas-de-sanidad-vegetal.pdf','https://vucerd.gob.do/media/2234/listado-salida-de-inspecci%C3%B3n-sanidad-vegetal.pdf'],'Obtain the current 090210 Japanese manufactured-tea requirement and any personal-post exception.',attempts=['Reviewed ministry import procedure and 2025 VUCE phytosanitary exclusion/inspection lists; attempted the SIREVUCE commodity lookup. No matching personal postal sencha exemption verified.'])
setrow('GT','not_verified','MAGA administers plant import permits under its plant-health law and import procedures, but the public product lookup did not establish the Japanese manufactured-tea classification. Regional Central American exemptions cannot be assumed to cover Japan.','No personal postal tea exemption verified in the published permit procedure or SEPA manual.','Guatemala MAGA VISAR',['https://www.tramites.gob.gt/servicio/2824/','https://www.maga.gob.gt/sitios/visar/facilitacion-de-comercio/','https://www.maga.gob.gt/sitios/visar/wp-content/uploads/2025/07/Manual-SEPA.pdf','https://sigie.maga.gob.gt/ConsultaProducto?tipo=2'],'Confirm processed Camellia tea from Japan and its personal-post permit/certificate requirements.',attempts=['Reviewed the official permit service, VISAR trade facilitation guidance, 2025 SEPA manual and SIGIE product lookup. No product-and-origin result confirming finished sencha was available.'])
setrow('HN','not_verified','Enacted SENASA quarantine regulation 001-2023 articles 5–12 applies permits and specified certification to regulated imports for commercial or other purposes, including consumption. Article 11 provides exempt-product lists; a matching finished-tea exemption or Japan commodity entry was not located.','Individual consumption is expressly included in permit applications; no postal small-quantity waiver established.','Honduras SENASA; Tribunal Superior de Cuentas official gazette',['https://www.tsc.gob.hn/web/leyes/Acuerdo-CD-SENASA-001-2023.pdf','https://sistemas.senasa.gob.hn/senasa/index.php/sub-direcciones/sub-direccion-tecnica-de-sanidad-vegetal/requisitos-fitosanitarios-para-la-importacion-de-vegetales'],'Does manufactured Japanese sencha appear on an article 11 exemption list, and otherwise which permit/phyto conditions apply?',attempts=['Read enacted 2023 regulation, specifically articles 7 and 11, and country commodity requirement tables; rejected the earlier 2022 draft as legal authority. No Japan/tea entry established.'])
setrow('SV','not_verified','MAG import authorization applies to regulated plant products. The March 2025 customs/MAG update still requires phytosanitary certificates for items labelled tea extract and powdered tea, but neither is the 090210 loose sencha product. A general processed-food exemption is therefore unsafe.','No confirmed personal postal exemption. The 2025 list covers small samples as well as other goods; small quantity alone is not clearance.','El Salvador MAG; Dirección General de Aduanas',['https://www.mag.gob.sv/guia-para-autorizaciones-de-importacion-de-productos-y-subproductos-de-origen-vegetal-en-el-centro-de-importaciones-y-exportaciones-de-el-salvador-ciex-el-salvador/','https://sitio.aduana.gob.sv/download/anexo-1-del-boletin-informativo-no-dga-003-2025/','https://sitio.aduana.gob.sv/wp-content/uploads/download-manager-files/ANEXO-1-BOLETIN-INF-No.-DGA-003-2025.pdf'],'Obtain MAG classification for HS 090210 loose manufactured tea, rather than extending the extract/powder entries.',attempts=['Reviewed MAG authorization procedure and current customs March 2025 MAG update (landing page updated April 2026). Distinguished tea entries under 2101/2103 from the product under 090210.'])
setrow('SR','not_verified','Suriname renewed its requirement for prior plant import permits, original phytosanitary certification and inspection in August 2026. Its guidance defines plant products in terms of unprocessed pest-bearing material; manufactured sencha is not explicitly classified.','General import notice contains no personal-post exemption; noncommercial plant imports are covered if regulated.','Suriname Ministry of Agriculture, Livestock and Fisheries NPPO',['https://gov.sr/wp-content/uploads/2026/08/Procedure-voor-de-invoer-van-planten-en-plantaardige-producten.jpg','https://gov.sr/wp-content/uploads/2023/08/LVV-IDB-Nieuwsbrief-uitgave-02.pdf'],'Does the NPPO classify steamed/dried retail tea as a regulated plant product under the 2020 Act?',attempts=['Read and OCRed the 14 August 2026 official import procedure notice, then compared the 2023 government explanation of plant-product scope. The finished-tea classification remains unresolved.'])
setrow('VG','not_verified','British Virgin Islands plant import conditions require a prior permit and phytosanitary certificate, but the published detailed conditions concern nursery plants, roots and growing material. That is not sufficient to classify manufactured dried tea as permit-controlled.','No personal postal processed-tea exception or explicit classification found.','British Virgin Islands Department of Agriculture',['https://bvi.gov.vg/sites/default/files/CONDITIONS%20FOR%20PLANT%20IMPORTATION.pdf','https://www.bvi.gov.vg/tags/agriculture?page=17'],'Confirm whether heat-processed retail tea is outside plant import controls or needs a permit and certificate.',attempts=['Read official plant-import conditions and agriculture notices; searched for tea/personal-mail scope. Excluded the draft Food Security and Sustainability Act from operative-law evidence.'])
setrow('GL','not_verified','Greenland has separate import arrangements; Danish or EU mainland plant-health exemptions cannot establish Greenland postal tea admissibility. Official Greenland food-import guidance did not settle the agricultural status of manufactured Camellia tea.','The available personal-food page is traveler-focused and is not extended to a Japanese online parcel.','Greenland food-import guidance from Danish Veterinary and Food Administration',['https://foedevarestyrelsen.dk/indgange/groenland/groenlandske-foedevarer/mad-med-paa-rejsen','https://foedevarestyrelsen.dk/indgange/groenland/groenlandske-foedevarer/indfoersel-samhandel-og-eksport/indfoersel-fra-tredjelande-og-graensekontrol'],'Identify the applicable Greenland plant-health rule and confirm sealed tea by post from Japan.',attempts=['Searched Naalakkersuisut and Greenland-specific Danish authority guidance for plant-health, tea and postal food imports; available travel and food-control material did not establish this plant-health route.'])
setrow('BL','not_verified','Saint Barthélemy operates territorial plant-import controls and invasive-species restrictions. The authority forms and plant allowlists concern flora and do not establish the treatment of manufactured tea; metropolitan EU tea rules are not substituted.','No verified personal-post rule for heat-processed Camellia tea.','Saint Barthélemy Agence Territoriale de l’Environnement',['https://www.agencedelenvironnement.fr/en/page/Identify-invasive-exotic-species','https://www.agencedelenvironnement.fr/en/page/promoting-native-flora','https://www.agencedelenvironnement.fr/en/formulaire/2'],'Does sealed manufactured tea fall outside the territorial plant permit system, and are any certificates needed?',attempts=['Reviewed ATE territorial invasive-plant rules, native-flora guidance and plant authorization forms; no processed-tea or personal-post provision found.'])
setrow('MF','not_verified','Saint Martin is outside the EU plant-health territory. A Dutch NPPO country sheet lists specific dried plant goods needing certification, but does not list tea and dates its substantive rules to 2012; that cannot verify the present Japanese postal route.','No current local manufactured-tea/personal-post confirmation; do not use mainland French rules automatically.','Netherlands NVWA country requirements for Saint Martin; French plant-health law',['https://www.nvwa.nl/site/binaries/site-content/collections/documents/fytosanitair/landeneisen/diverse-producten/saint-martin-diverse-producten-exporteisen/Saint-Martin_Diverse_producten_exporteisen_1.0.pdf','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000343648/'],'Confirm current Saint Martin applicability and finished-tea treatment for direct Japanese personal mail.',attempts=['Reviewed the full NVWA Saint Martin country sheet, including its 2012/2013 revision history and third-country plant-product list; searched French local import guidance. Current tea-specific scope remains unverified.'])
for code,local in [('GF','https://daaf.guyane.agriculture.gouv.fr/IMG/pdf/900903_controle_vgtx_cle026c57.pdf'),('GP','https://daaf.guadeloupe.agriculture.gouv.fr/l-envoi-de-vegetaux-de-la-guadeloupe-vers-la-france-et-les-autres-pays-de-l-a1199.html'),('MQ','https://daaf.martinique.agriculture.gouv.fr/importation-des-vegetaux-et-produits-vegetaux-a362.html')]:
 setrow(code,'not_verified','The French overseas 3 September 1990 plant-health order defines controlled plant products by processing and listed commodity. Its special dried-tea entry is restricted to Réunion; that condition must not be imposed here. Current local classification of manufactured Japanese sencha has not been established.','These destinations are separate from the EU plant-health territory. Neither metropolitan EU clearance nor a passenger allowance proves this personal postal route.','French Ministry of Agriculture; local DAAF',['https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000343648/',local],'Confirm that heat-processed retail sencha is outside the locally controlled commodity list and whether any personal-post documentation applies.',attempts=['Read the 1990 overseas plant-health order and its territory-specific dried-tea entry; reviewed local DAAF guidance. The Réunion-only condition does not settle this territory’s current manufactured-tea scope.'])
setrow('PM','not_verified','Saint Pierre and Miquelon has its own Code rural plant-import authorization and certification framework, with plant products defined by limited processing. The local Newfoundland exception does not cover direct Japanese parcels. No manufactured-sencha classification was established.','Rules are territory-specific; professional registration requirements alone do not resolve individual mail permits.','French Code rural, Saint Pierre and Miquelon provisions; prefecture',['https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006071367/LEGISCTA000032693959/','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035419827','https://www.saint-pierre-et-miquelon.gouv.fr/contenu/telechargement/812/4383/file/Recueil%20administratif%20%20-%20Septembre%202009.pdf'],'Does steamed/dried retail sencha fall outside regulated unprocessed/simply prepared plant products; if not, which personal-post authorizations apply?',attempts=['Reviewed current territory-specific Code rural provisions D274-26 onwards and the prefectural import order; distinguished professional registration and Newfoundland concessions from the Japanese personal postal case.'])
setrow('EC','permit_required','Ecuador’s national COMEX 009-2022 row 616 explicitly requires an Agrocalidad import permit and DDA for retail green tea (090210). The quarantine manual requires operator registration, prior permit, origin certification and arrival inspection for regulated postal consignments. A processed-product exemption requires an Agrocalidad categorization decision; it cannot be assumed from the general Andean category alone.','Quarantine manual section 9 expressly covers natural persons using postal/courier services. The separate 1 kg traveler allowance is not applied to mail.','Ecuador Agrocalidad; COMEX',['https://www.agrocalidad.gob.ec/wp-content/uploads/2024/10/2RESOL1.pdf','https://www.agrocalidad.gob.ec/wp-content/uploads/2024/10/Resol_133_Manual-general-de-cuarentena-vegetal.pdf','https://www.agrocalidad.gob.ec/direccion-de-control-fitosanitario/'],'Request Agrocalidad categorization for this manufactured sencha if seeking exemption; absent that decision follow the retail-green-tea permit entry.',attempts=['Cross-checked Andean Resolution 1475 against the national COMEX tariff list: row 616 expressly controls 090210. Read quarantine manual section 9 on postal consignments and its processed-product categorization note, and rejected the baggage-only 1 kg allowance.'])
save()
country_attempts={
 'AG':['Reviewed PPU import guidance and the 27 August 2020 commodity-status table, including processed-food examples. No explicit heat-processed Camellia tea classification or small postal waiver found.'],
 'KN':['Read SKNIS plant import guidance and its permit/small-quantity passage. Distinguished its tea-export example from import permission; no manufactured-tea personal-post exemption established.'],
 'TT':['Reviewed ministry notice expressly covering online/mail plant purchases and Plant Protection subsidiary regulations. Preserved-fruit/vegetable exceptions do not expressly resolve manufactured tea.'],
 'AW':['Read the Aruba 2022 import requirements reproduced by the German NPPO JKI, including the tea economic-licence entry. Searched for personal postal and agricultural scope; no definitive plant-health tea ruling found.'],
 'CW':['Reviewed Curaçao customs forbidden-goods and general clearance procedures. Plant/flower permit entries do not classify tea, and personal customs treatment does not establish a plant-health exemption.'],
 'BQ':['Read Bonaire’s dried-herb import notice; it specifically concerns Venezuela. Searched Japanese tea rules and Saba/Sint Eustatius coverage without finding a shared personal-post exemption.'],
 'SX':['Reviewed Sint Maarten LVV plant-import guidance and application material. No manufactured-tea or personal-mail entry identified.'],
 'GU':['Read Guam administrative regulations 10101/10103/10120 and Biosecurity Division guidance. The stored-dried-food allowance leaves the separate permit classification unresolved.'],
 'MP':['Read current CNMI administrative code 85-60.2, especially sections 201/202/204/238, and Customs USPS guidance. Dried food is admitted subject to inspection, but permit classification remains unclear.'],
 'NI':['Downloaded and OCRed the operative NTON 11003 publication, checking its explicit all-quantity, online and postal scope and plant-product categories; no clear finished-sencha exemption found.'],
 'AR':['Compared SENASA AFIDI/risk-classification rules with the personal online food procedure. The ANMAT simplification does not resolve the SENASA category or AFIDI for this Japanese sencha.'],
 'BS':['Read BAHFSA tea declaration FAQ, all-channel plant-import rules and food-conditions appendix. Confirmed mail/courier scope but could not classify manufactured sencha under processed-product exceptions.'],
 'BB':['Reviewed the government plant-import procedure and personal-consumption/mail form options. Searched operative tea processing exemptions; did not rely on a draft replacement Plant Protection Act.'],
 'JM':['Read PQPI permit application and import-process brochures, including personal JSWIFT path; attempted the commodity requirements table. No finished-tea entry or personal postal exemption confirmed.'],
 'LC':['Read the Plant Protection Act product definition and regulations 12 (mail) and 16 (permit). The pest-carrying threshold leaves heat-processed retail tea classification unresolved.'],
 'DM':['Read the ministry import permit procedure, sample permit and Plant Protection Act. Preserved-fruit exceptions do not clearly cover manufactured Camellia tea; no personal postal waiver found.'],
 'GD':['Reviewed official NPPO profile and government-notified WTO description of Grenada plant import controls; searched manufactured-tea and personal postal exceptions. No commodity-specific conclusion established.'],
 'VC':['Read 2015 Plant Protection Act, including section 15 expressly covering postal services, and government-notified import licensing requirements. No manufactured-tea processing exemption identified.'],
 'MS':['Read the Plant Protection Act and current 2025 agricultural import amendment notice. Citrus amendments do not classify tea, and the older preserved-fruit provision does not establish a postal tea exception.'],
 'TC':['Compared government import portal with Agriculture resident import guidance; checked the published 25 lb produce threshold. Its scope does not establish a tea or personal postal allowance.']
}
for code,attempts in country_attempts.items():rows[code]['researchAttempts']=attempts
save()
setrow('CL','conditional','Japan’s current NPPO postal table explicitly marks manufactured green tea to Chile ◎: no Japanese phytosanitary export certificate required. SAG category-1 guidance supports entry of sufficiently processed plant foods; retain the sealed finished-tea packaging and manufacturing description for any inspection. This conclusion is for manufactured sencha, not raw merely dried leaf material.','The 21 April 2026 MAFF table expressly covers postal shipments. No agricultural personal tea weight cap was identified.','Japan MAFF Plant Protection Station, reporting Chilean requirements; Chile SAG',['https://www.maff.go.jp/pps/j/search/e_hayami_yubin.pdf','https://www.maff.go.jp/pps/j/search/ekuni/sa/chile/index.html','https://www.sag.gob.cl/sites/default/files/res._1.284_de_2021_con_anexo.pdf'],'SAG’s table separately names dried-and-crushed tea; the exact Japanese manufactured-green-tea postal guidance supplies the product-specific clearance. Preserve steaming/finished-product evidence if SAG requests classification.',attempts=['Read SAG processing categories and the current Japanese NPPO postal matrix. Reconciled the dried-and-crushed example with the explicit manufactured-green-tea ◎ entry on the first page (Chile is printed as spaced チ リ).'])
setrow('GF','not_verified','Guyane order R03-2021-04-26-00003 bans personal imports of regulated plants/plant products in any quantity from all origins, subject to an approved derogation. Its scope uses the 1990 definition of unprocessed or simply prepared plant products. Whether steaming/manufacturing removes this retail sencha from that definition remains unresolved.','The order covers personal introduction/importation broadly, not merely a passenger allowance; no postal exemption established.','Guyane prefecture/DGTM; French Ministry of Agriculture',['https://www.guyane.gouv.fr/content/download/18708/131303/file/recueil-r03-2021-109-recueil-des-actes-administratifs.pdf','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000343648/','https://info.agriculture.gouv.fr/boagri/instruction-2025-102/telechargement'],'Confirm finished heat-processed sencha is outside the 1990 plant-product definition; otherwise obtain the local prior derogation before any personal parcel.',attempts=['Read the 1990 overseas rule and 2025 ministry instruction retaining pre-2019 law pending an overseas decree. Located the official 2021 personal-import order; the official PDF was inaccessible, so checked its reproduced legal text (articles 1–2) against the official indexed title and number. No 2025/2026 processed-tea exemption found.'])
setrow('MQ','not_verified','Martinique DAAF expressly cites the 22 November 2004 order prohibiting personal plant-product imports from all origins, using the 1990 definition of unprocessed or simply prepared material. The effect on factory-steamed/dried sencha is not explicitly resolved; the Réunion-specific dried-tea rule is not applied here.','The local rule concerns personal introductions/imports generally; no manufactured-tea postal exception established.','Martinique DAAF; French Ministry of Agriculture',['https://daaf.martinique.agriculture.gouv.fr/quels-sont-les-vegetaux-soumis-a-un-contole-au-pec-lors-de-leur-introduction-a373.html','https://daaf.martinique.agriculture.gouv.fr/importation-des-vegetaux-et-produits-vegetaux-a362.html','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000343648/','https://info.agriculture.gouv.fr/boagri/instruction-2025-102/telechargement'],'Obtain DAAF confirmation that finished manufactured sencha is outside the regulated plant-product definition and personal-import restriction.',attempts=['Reviewed the DAAF controlled-goods FAQ expressly citing the 2004 personal-import ban, the 1990 product definition and the ministry’s 2025 transitional-law instruction. Searched current local processing exclusions without finding a finished-tea ruling.'])
rows['GP']['evidenceUrls']=['https://daaf.guadeloupe.agriculture.gouv.fr/controle-des-importations-de-denrees-animales-et-vegetales-en-guadeloupe-a128.html','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000343648/','https://info.agriculture.gouv.fr/boagri/instruction-2025-102/telechargement']
rows['GP']['researchAttempts'].append('Second review checked local import-control guidance and the 2025 ministry instruction retaining pre-2019 overseas law. The March 2025 tea exemption found concerns VAT only and cannot establish phytosanitary clearance.')
for code in ['BL','MF']:
 rows[code]['evidenceUrls'].append('https://info.agriculture.gouv.fr/boagri/instruction-2025-102/telechargement')
 rows[code]['researchAttempts'].append('Second review searched 2025/2026 local tea exclusions. The 2025 ministry overseas instruction explicitly excludes Saint Barthélemy/Saint Martin regulations from its analysis; it does not extend a mainland exemption.')
rows['PM']['evidenceUrls'][0]='https://www.legifrance.gouv.fr/codes/id/LEGISCTA000032693993'
rows['PM']['researchAttempts'].append('Second review confirmed current August 2026 Code rural text D274-29 and D274-30: certificate controls and the Newfoundland-only personal exception remain; no processed-sencha ruling found.')
save()
