import { Subscription } from 'rxjs';
import type { TransactionsState } from './types';
import type { AccountHistory, HistoryItem } from '@sora-substrate/sdk';
declare const mutations: {
  setActiveTxsSubscription(state: TransactionsState, subscription: NodeJS.Timeout | number): void;
  resetActiveTxs(state: TransactionsState): void;
  addActiveTx(state: TransactionsState, id: string): void;
  removeActiveTxs(state: TransactionsState, ids: Array<string>): void;
  removeHistoryByIds(state: TransactionsState, ids: Array<string>): void;
  setTxDetailsId(state: TransactionsState, id: string): void;
  resetTxDetailsId(state: TransactionsState): void;
  getHistory(state: TransactionsState): Promise<void>;
  setExternalHistory(state: TransactionsState, history: AccountHistory<HistoryItem>): void;
  setExternalHistoryUpdates(state: TransactionsState, history: AccountHistory<HistoryItem>): void;
  saveExternalHistoryUpdates(state: TransactionsState, flag: boolean): void;
  setExternalHistoryTotal(state: TransactionsState, total?: any): void;
  resetExternalHistory(state: TransactionsState): void;
  setExternalHistorySubscription(state: TransactionsState, subscription: VoidFunction): void;
  resetExternalHistorySubscription(state: TransactionsState): void;
  setConfirmTxDialogDisabled(state: TransactionsState, flag: boolean): void;
  setSignTxDialogDisabled(state: TransactionsState, flag: boolean): void;
  setSignTxDialogVisibility(state: TransactionsState, visibility: boolean): void;
  setPendingMstTxsSubscription(state: TransactionsState, subscription: Subscription | null): void;
  resetPendingMstTxsSubscription(state: TransactionsState): void;
  setPendingMstTransactions(state: TransactionsState, transactions: HistoryItem[]): void;
};
export default mutations;
