export type RouteAuditMode = 'public' | 'protected-redirect' | 'protected-auth';

export type RouteAuditCase = {
  id: string;
  hash: string;
  acceptedHashes: string[];
  expectedClassToken: string;
  additionalExpectedClassTokens?: string[];
  extraAllowedConsolePatterns?: RegExp[];
  skipCorruptionCheck?: boolean;
  requiresAuth: boolean;
  mode: RouteAuditMode;
  liveEligible: boolean;
  snapshotEligible: boolean;
};

export const AUTHENTICATED_WALLET_STATE = {
  address: 'cnRXua6zs8TaE87BQFL6uWVbT2g6GXsUjwk6PTvL6UHcHDCvo',
  name: 'E2E Wallet',
  source: 'polkadot-js',
  isExternal: 'false',
} as const;

const REFERRAL_ADDRESS = AUTHENTICATED_WALLET_STATE.address;

const publicRoutes: RouteAuditCase[] = [
  {
    id: 'swap',
    hash: '#/swap',
    acceptedHashes: ['#/swap'],
    expectedClassToken: 'app-main--swap',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'trade',
    hash: '#/trade',
    acceptedHashes: ['#/trade'],
    expectedClassToken: 'app-main--orderbook',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'stats',
    hash: '#/stats',
    acceptedHashes: ['#/stats'],
    expectedClassToken: 'app-main--stats',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'burn',
    hash: '#/burn',
    acceptedHashes: ['#/burn'],
    expectedClassToken: 'app-main--burn',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'bridge',
    hash: '#/bridge',
    acceptedHashes: ['#/bridge'],
    expectedClassToken: 'app-main--bridge',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'bridge-sccp',
    hash: '#/bridge/sccp',
    acceptedHashes: ['#/swap'],
    expectedClassToken: 'app-main--swap',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'deposit',
    hash: '#/deposit',
    acceptedHashes: ['#/deposit'],
    expectedClassToken: 'app-main--depositoptions',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'deposit-transfer-from-cex',
    hash: '#/deposit/transfer-from-cex',
    acceptedHashes: ['#/deposit/transfer-from-cex'],
    expectedClassToken: 'app-main--cedestore',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore',
    hash: '#/explore',
    acceptedHashes: ['#/explore', '#/explore/tokens'],
    expectedClassToken: 'app-main--explore/tokens',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore-tokens',
    hash: '#/explore/tokens',
    acceptedHashes: ['#/explore/tokens'],
    expectedClassToken: 'app-main--explore/tokens',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore-demeter-staking',
    hash: '#/explore/demeter/staking',
    acceptedHashes: ['#/explore/demeter/staking'],
    expectedClassToken: 'app-main--explore/staking',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore-demeter-farming',
    hash: '#/explore/demeter/farming',
    acceptedHashes: ['#/explore/demeter/farming'],
    expectedClassToken: 'app-main--explore/farming',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore-pools',
    hash: '#/explore/pools',
    acceptedHashes: ['#/explore/pools'],
    expectedClassToken: 'app-main--explore/pools',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'explore-books',
    hash: '#/explore/books',
    acceptedHashes: ['#/explore/books'],
    expectedClassToken: 'app-main--explore/books',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'points',
    hash: '#/points',
    acceptedHashes: ['#/points'],
    expectedClassToken: 'app-main--pointsystemwrapper',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'rewards',
    hash: '#/rewards',
    acceptedHashes: ['#/rewards'],
    expectedClassToken: 'app-main--rewards',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'referral-program',
    hash: `#/referral/${REFERRAL_ADDRESS}`,
    acceptedHashes: [`#/referral/${REFERRAL_ADDRESS}`],
    expectedClassToken: 'app-main--referralprogram',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'pool',
    hash: '#/pool',
    acceptedHashes: ['#/pool'],
    expectedClassToken: 'app-main--pool',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'staking',
    hash: '#/staking',
    acceptedHashes: ['#/staking', '#/staking/list'],
    expectedClassToken: 'app-main--staking',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'staking-list',
    hash: '#/staking/list',
    acceptedHashes: ['#/staking/list'],
    expectedClassToken: 'app-main--staking',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'staking-sora',
    hash: '#/staking/sora',
    acceptedHashes: ['#/staking/sora'],
    expectedClassToken: 'app-main--overview',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'staking-sora-validators-type',
    hash: '#/staking/sora/validators/type',
    acceptedHashes: ['#/staking/sora/validators/type', '#/staking/sora'],
    expectedClassToken: 'app-main--validatorstype',
    additionalExpectedClassTokens: ['app-main--selectvalidators', 'app-main--validatorsselect', 'app-main--overview'],
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'staking-sora-validators-select',
    hash: '#/staking/sora/validators/select',
    acceptedHashes: ['#/staking/sora/validators/select', '#/staking/sora'],
    expectedClassToken: 'app-main--validatorsselect',
    additionalExpectedClassTokens: ['app-main--selectvalidators', 'app-main--validatorstype', 'app-main--overview'],
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'wallet',
    hash: '#/wallet',
    acceptedHashes: ['#/wallet'],
    expectedClassToken: 'app-main--wallet',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'kensetsu',
    hash: '#/kensetsu',
    acceptedHashes: ['#/kensetsu'],
    expectedClassToken: 'app-main--vaults',
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'dashboard-owner',
    hash: '#/dashboard/owner',
    acceptedHashes: ['#/dashboard/owner', '#/swap'],
    expectedClassToken: 'app-main--assetowner',
    additionalExpectedClassTokens: ['app-main--swap'],
    extraAllowedConsolePatterns: [/status of 404 \(Not Found\)/i],
    requiresAuth: false,
    mode: 'public',
    liveEligible: true,
    snapshotEligible: false,
  },
];

const protectedRedirectRoutes: RouteAuditCase[] = [
  {
    id: 'bridge-history-redirect',
    hash: '#/bridge/history',
    acceptedHashes: ['#/bridge'],
    expectedClassToken: 'app-main--bridge',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'bridge-transaction-redirect',
    hash: '#/bridge/transaction',
    acceptedHashes: ['#/bridge', '#/bridge/'],
    expectedClassToken: 'app-main--bridge',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'deposit-history-redirect',
    hash: '#/deposit/history',
    acceptedHashes: ['#/wallet'],
    expectedClassToken: 'app-main--wallet',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'referral-bond-redirect',
    hash: '#/referral/bond',
    acceptedHashes: ['#/referral/bond'],
    expectedClassToken: 'app-main--referralprogram',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'referral-unbond-redirect',
    hash: '#/referral/unbond',
    acceptedHashes: ['#/referral/unbond'],
    expectedClassToken: 'app-main--referralprogram',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'pool-add-redirect',
    hash: '#/pool/add',
    acceptedHashes: ['#/wallet'],
    expectedClassToken: 'app-main--wallet',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'kensetsu-details-redirect',
    hash: '#/kensetsu/0',
    acceptedHashes: ['#/wallet'],
    expectedClassToken: 'app-main--wallet',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'dashboard-owner-details-redirect',
    hash: '#/dashboard/owner/XOR',
    acceptedHashes: ['#/wallet'],
    expectedClassToken: 'app-main--wallet',
    requiresAuth: true,
    mode: 'protected-redirect',
    liveEligible: true,
    snapshotEligible: false,
  },
];

const protectedAuthRoutes: RouteAuditCase[] = [
  {
    id: 'bridge-history',
    hash: '#/bridge/history',
    acceptedHashes: ['#/bridge/history'],
    expectedClassToken: 'app-main--bridgetransactionshistory',
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'bridge-transaction',
    hash: '#/bridge/transaction',
    acceptedHashes: ['#/bridge/transaction', '#/bridge', '#/bridge/'],
    expectedClassToken: 'app-main--bridge',
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: false,
  },
  {
    id: 'deposit-history',
    hash: '#/deposit/history',
    acceptedHashes: ['#/deposit/history'],
    expectedClassToken: 'app-main--deposittxhistory',
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'referral-bond',
    hash: '#/referral/bond',
    acceptedHashes: ['#/referral/bond'],
    expectedClassToken: 'app-main--referralprogram',
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'referral-unbond',
    hash: '#/referral/unbond',
    acceptedHashes: ['#/referral/unbond'],
    expectedClassToken: 'app-main--referralprogram',
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'pool-add',
    hash: '#/pool/add',
    acceptedHashes: ['#/pool/add'],
    expectedClassToken: 'app-main--addliquidity',
    skipCorruptionCheck: true,
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'kensetsu-details',
    hash: '#/kensetsu/0',
    acceptedHashes: ['#/kensetsu/0', '#/kensetsu', '#/kensetsu/'],
    expectedClassToken: 'app-main--vaults',
    additionalExpectedClassTokens: ['app-main--vaultdetails'],
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: true,
  },
  {
    id: 'dashboard-owner-details',
    hash: '#/dashboard/owner/XOR',
    acceptedHashes: ['#/dashboard/owner/XOR', '#/dashboard/owner', '#/swap'],
    expectedClassToken: 'app-main--assetownerdetails',
    additionalExpectedClassTokens: ['app-main--assetowner', 'app-main--swap'],
    requiresAuth: true,
    mode: 'protected-auth',
    liveEligible: true,
    snapshotEligible: false,
  },
];

export const publicRouteAuditCases = publicRoutes;
export const protectedRedirectRouteAuditCases = protectedRedirectRoutes;
export const protectedAuthRouteAuditCases = protectedAuthRoutes;

export const routeAuditCases: RouteAuditCase[] = [
  ...publicRouteAuditCases,
  ...protectedRedirectRouteAuditCases,
  ...protectedAuthRouteAuditCases,
];

export const snapshotRouteAuditCases = routeAuditCases.filter((route) => route.snapshotEligible);

export const liveRouteAuditCases = routeAuditCases.filter((route) => route.liveEligible);
