import { IndexerType, Theme, SoraNetwork, WalletPermissions, WalletAssetFilters } from '../../consts';
import { Alert, ApiKeysObject, FilterOptions, IndexerState } from '../../types/common';
import { Currency, CurrencyFields, FiatExchangeRateObject } from '../../types/currency';
import { NetworkFeesObject } from '@sora-substrate/sdk';
import { NFTStorage } from 'nft.storage';
import { Subscription } from 'rxjs';

export type SettingsState = {
  apiKeys: ApiKeysObject;
  alerts: Array<Alert>;
  allowTopUpAlert: boolean;
  isWalletLoaded: boolean;
  indexerType: IndexerType;
  indexers: Record<IndexerType, IndexerState>;
  permissions: WalletPermissions;
  filters: WalletAssetFilters;
  allowFeePopup: boolean;
  soraNetwork: Nullable<SoraNetwork>;
  networkFees: NetworkFeesObject;
  shouldBalanceBeHidden: boolean;
  feeMultiplier: number;
  runtimeVersion: number;
  blockNumber: number;
  blockNumberSubscription: Nullable<Subscription>;
  feeMultiplierAndRuntimeSubscriptions: Nullable<Subscription>;
  nftStorage: Nullable<NFTStorage>;
  currency: Currency;
  currencies: Array<CurrencyFields>;
  fiatExchangeRateObject: FiatExchangeRateObject;
  exchangeRateUnsubFn: Nullable<VoidFunction>;
  assetsFilter: FilterOptions;
  isMSTAvailable: boolean;
  theme: Theme;
};
