/**
 * `navigator.language` values, f.e. ('es', 'eu-ES')
 */
export enum Language {
  EN = 'en',
  RU = 'ru',
  CS = 'cs',
  DE = 'de',
  ES = 'es',
  FR = 'fr',
  ID = 'id',
  IT = 'it',
  NL = 'nl',
  PL = 'pl',
  SR = 'sr',
  VI = 'vi',
  ZH_CN = 'zh-CN',
  ZH_TW = 'zh-TW',
  HE = 'he',
  AR = 'ar',
  UR = 'ur',
  KM = 'km',
  TH = 'th',
  PIS = 'pis',
  MY = 'my',
  AKK = 'akk',
  EGY = 'egy',
  UK = 'uk',
  BA = 'ba',
  DZ = 'dz',
  MN = 'mn',
  KK = 'kk',
  TT = 'tt',
  DV = 'dv',
  AM = 'am',
}

export const Languages = [
  { key: Language.EN, value: 'English', name: 'English (UK)' },
  { key: Language.ZH_CN, value: 'Chinese Simplified', name: '简体中文' },
  { key: Language.ZH_TW, value: 'Chinese Traditional', name: '繁體中文' },
  { key: Language.CS, value: 'Czech', name: 'Čeština' },
  { key: Language.NL, value: 'Dutch', name: 'Nederlands' },
  { key: Language.FR, value: 'French', name: 'Français' },
  { key: Language.DE, value: 'German', name: 'Deutsch' },
  { key: Language.ID, value: 'Indonesian', name: 'bahasa Indonesia' },
  { key: Language.IT, value: 'Italian', name: 'Italiano' },
  { key: Language.PL, value: 'Polish', name: 'Polski' },
  { key: Language.RU, value: 'Russian', name: 'Русский' },
  { key: Language.SR, value: 'Serbian', name: 'Српски' },
  { key: Language.ES, value: 'Spanish', name: 'Español' },
  { key: Language.VI, value: 'Vietnamese', name: 'Tiếng Việt' },
  { key: Language.HE, value: 'Hebrew', name: 'עברית' },
  { key: Language.AR, value: 'Arabic', name: 'العربية' },
  { key: Language.UR, value: 'Urdu', name: 'اردو' },
  { key: Language.KM, value: 'Khmer', name: 'ភាសាខ្មែរ' },
  { key: Language.TH, value: 'Thai', name: 'ไทย' },
  { key: Language.PIS, value: 'Solomon Islands Pidgin', name: 'Solomon Pijin' },
  { key: Language.MY, value: 'Burmese', name: 'ဗမာစာ' },
  { key: Language.AKK, value: 'Akkadian (Cuneiform)', name: 'Akkadian' },
  { key: Language.EGY, value: 'Egyptian (Hieroglyphs)', name: '𓂋𓏤𓈖𓎼𓊪𓏏𓊖' },
  { key: Language.UK, value: 'Ukrainian', name: 'Українська' },
  { key: Language.BA, value: 'Bashkir', name: 'Башҡортса' },
  { key: Language.DZ, value: 'Dzongkha', name: 'རྫོང་ཁ' },
  { key: Language.MN, value: 'Mongolian', name: 'Монгол' },
  { key: Language.KK, value: 'Kazakh', name: 'Қазақ тілі' },
  { key: Language.TT, value: 'Tatar', name: 'Татарча' },
  { key: Language.DV, value: 'Divehi', name: 'ދިވެހި' },
  { key: Language.AM, value: 'Amharic', name: 'አማርኛ' },
];
