export enum PageNames {
  Swap = 'Swap',
  Pool = 'Pool',
  Stats = 'Stats',
  Wallet = 'Wallet',
  AddLiquidity = 'AddLiquidity',
  Farming = 'Farming',
  Rewards = 'Rewards',
  ReferralProgram = 'ReferralProgram',
  PointSystemWrapper = 'PointSystemWrapper',
  RewardsTabs = 'RewardsTabs',
  ReferralBonding = 'ReferralBonding',
  ReferralUnbonding = 'ReferralUnbonding',
  BridgeContainer = 'BridgeContainer',
  Bridge = 'Bridge',
  Sccp = 'Sccp',
  BridgeTransaction = 'BridgeTransaction',
  BridgeTransactionsHistory = 'BridgeTransactionsHistory',
  Tokens = 'Tokens',
  DepositOptions = 'DepositOptions',
  DepositTxHistory = 'DepositTxHistory',
  CedeStore = 'CedeStore',
  StakingContainer = 'StakingContainer',
  ExploreContainer = 'Explore/Container',
  ExploreTokens = 'Explore/Tokens',
  ExploreDemeter = 'Explore/Demeter',
  ExploreFarming = 'Explore/Farming',
  ExploreStaking = 'Explore/Staking',
  ExplorePools = 'Explore/Pools',
  ExploreBooks = 'Explore/Books',
  OrderBook = 'OrderBook',
  LimitOrderBuy = 'OrderBook/LimitOrderBuy',
  LimitOrderSell = 'OrderBook/LimitOrderSell',
  AssetOwnerContainer = 'AssetOwnerContainer',
  VaultsContainer = 'VaultsContainer',
  Burn = 'Burn',
}

export enum RouteNames {
  WalletConnection = 'WalletConnection',
  WalletSend = 'WalletSend',
  Wallet = 'Wallet',
  WalletAssetDetails = 'WalletAssetDetails',
  CreateToken = 'CreateToken',
  ReceiveToken = 'ReceiveToken',
  AddAsset = 'AddAsset',
  SelectAsset = 'SelectAsset',
}

export const BridgeChildPages = [PageNames.Bridge, PageNames.BridgeTransaction, PageNames.BridgeTransactionsHistory];
